CONTRIBUTING.md
=> docs: update readme about how to change role locally

CONTRIBUTING.md, README.md
@dzmitry-varabei please review
=> docs: update docs

src/routes/profile/index.ts, src/routes/profile/me.ts
feat: add api/profile/registry POST to enable saving user info during the registry
=> feat: add api/profile/registry POST

serverless/github-task-checker/handler.ts, serverless/github-task-checker/package.json
2.1.  + Download repository (master branch) as zip and unpack
2.2.  + Install deps
2.3.  + Run "npm test"
2.4.  - Save result to DB
**the return result from the function looks like this**:
```
{
"statusCode": 200,
"body": {
"passed": 100,
"failed": null,
"time": "40ms",
"exitCode": 0
}
}
```
=> feat: github task checker

serverless/github-task-checker/htmlTask.ts, serverless/github-task-checker/package-lock.json, serverless/github-task-checker/package.json, serverless/github-task-checker/tsconfig.json
Reverts rolling-scopes/rsschool-app#104
=> Revert "Revert "feat: add html task checker""

client/src/pages/index.tsx
- added a link to a google form for feedback on rs school,
- renamed menu items about feedback on students/mentors and gratitude for a clearer understanding
=> add link to feedback on rs school

client/src/pages/profile/index.tsx
- added public feedback date in profile, 
- updated public feedback layout in profile
=> fix: public feedback view in profile

client/src/pages/course/score.tsx
- made fixed "rank" & "github" columns on the left side of score table
- made fixed header of score table
- reduced cell size and font size
=> fix: score table view

client/src/components/Feedback.tsx, client/src/components/Help.tsx, client/src/components/index.tsx, client/src/pages/index.tsx
extracted 'Help' menu items from 'Feedback' items to separate section;
put 'Help' and 'Feedback' into separate components
=> feat: extract help from feedback

client/src/components/AdminSider.tsx, client/src/components/index.tsx, client/src/pages/index.tsx, client/src/styles/main.scss
extract admin menu to separate component,
update the layout of index page by adding 'Admin Area' sidebar
=> move admin menu to sidebar

client/src/components/Feedback.tsx, client/src/components/FooterLayout.tsx, client/src/components/Help.tsx, client/src/components/SocialNetworks.tsx, client/src/components/index.tsx, client/src/pages/index.tsx, client/src/styles/main.scss
add a footer with sections:
- feedback
- help
- join us
=> feat: add footer

client/src/components/AdminSider.tsx, client/src/pages/admin/courses.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/registrations.tsx, client/src/pages/admin/stages.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/admin/users.tsx
- make admin sider is folded by default
- add admin sider to the pages:
- courses
- events
- registrations
- stages
- tasks
- users
=> feat: add admin sider to admin pages

client/src/pages/profile/edit.tsx
Attempt to fix #190
I've added input for English Level, but probably possible values should be more strict, so I'm open for suggestions
=> Add possibility to edit english level in profile

client/package-lock.json, client/package.json, yarn.lock
=> fix: add moment as dependency

client/package.json, client/src/components/Table/sorters.ts, client/src/pages/course/admin/mentors.tsx, client/src/services/formatter.ts, server/src/services/courseService.ts, yarn.lock
feat: display when last task was checked
fix: showing mentors without any checked task
Fixes https://github.com/rolling-scopes/rsschool-app/issues/237
=> Mentor dashboard improvements

client/src/components/Rating.tsx, client/src/components/index.tsx, client/src/pages/course/mentor/stage-interview-feedback.tsx, client/src/pages/course/mentor/stage-interviews.tsx, client/src/pages/profile/index.tsx, client/src/services/user.ts, common/models/index.ts, common/models/stage-interview-feedback.ts, common/models/user.ts, server/src/models/stageInterview.ts, server/src/routes/profile/user.ts, server/src/services/stageInterviews.ts
=> feat: add stage interview feedback rating to student profile

client/src/pages/registry/mentor.tsx
Changed the label to "About Yourself"
=> fix(typo): updated label to "About Yourself"

client/src/pages/admin/tasks.tsx, client/src/pages/course/schedule.tsx, client/src/pages/course/student/auto-test.tsx, client/src/services/course.ts, client/src/services/task.ts, server/src/models/task.ts, server/src/routes/course/student.ts, server/src/routes/course/taskVerification.ts
Added this codewars task for stage 1:
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars-stage-1.md
=> feat: add another codewars task

client/src/pages/course/mentor/interview-corejs.tsx
=> fix: translate interview page for mentors

client/src/pages/course/schedule.tsx
fixes https://github.com/rolling-scopes/rsschool-app/issues/382
=> fix: use default timezone from browser

client/src/components/Table/PersonCell.tsx, client/src/pages/course/admin/mentors.tsx, client/src/pages/course/admin/students.tsx, client/src/pages/course/admin/users.tsx, client/src/pages/course/schedule.tsx, server/src/services/course.service.ts
fix: user/student/mentor search
=> fix: schedule date rendering

client/src/pages/index.tsx, server/src/services/stageInterview.service.ts
Reverts rolling-scopes/rsschool-app#396
=> Revert "fix: remove expel from main page"

client/package-lock.json, client/package.json, client/src/components/Dashboard/CommonDashboardCard.tsx, client/src/components/Dashboard/MainStatsCard.tsx, client/src/components/Dashboard/MentorCard.tsx, client/src/components/Dashboard/NextEventCard.tsx, client/src/components/Dashboard/TasksStatsCard.tsx, client/src/components/Dashboard/TasksStatsModal.tsx, client/src/components/Dashboard/index.ts, client/src/components/Dashboard/renderers.tsx, client/src/next.config.js, client/src/pages/course/student/dashboard.tsx, client/src/pages/index.tsx, common/models/profile.ts
Create a page with a set of widgets which display all useful information for a student at glance.
Implement the widgets:
- Score
- Mentor
- Tasks statistics
- Next event
=> Feature: add student dashboard

client/src/components/Dashboard/MainStatsCard.tsx, client/src/components/Dashboard/NextEventCard.tsx, client/src/pages/course/student/dashboard.tsx, client/src/services/course.ts
Added the correct student position
=> fix: fix problem with position students

client/src/pages/course/mentor/submit-review-jury.tsx
Submit now clears all fields except the field with the task.
=> feat: improve clearance of form fields  on submit

client/src/__tests__/__snapshots__/ProfilePage.test.tsx.snap, client/src/components/Profile/StudentStatsCard.tsx, client/src/components/Profile/__test__/StudentStatsCard.test.tsx, client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap, client/src/pages/profile/index.tsx, client/src/utils/profile-check.ts
SelfExpel no longer appears on the profiles, the owner of which is not the user who is viewing themю
=> Fix self expel presence on public profile

client/src/pages/admin/tasks.tsx
Now tasks on the task management page can be found by their name
=> Feature: search by taskname to task management page

client/src/components/CrossCheckComments.tsx, client/src/components/__tests__/CrossCheckComments.test.tsx, client/src/components/__tests__/__snapshots__/CrossCheckComments.test.tsx.snap, client/src/components/index.tsx, client/src/pages/course/student/cross-check-submit.tsx, server/src/services/taskResults.service.ts
The score for the task is now displayed in anonymous feedbacks.
=> Feature: show score from anonymous feedback

client/src/components/Footer/Donation.tsx, client/src/components/Footer/FooterLayout.tsx
Now donators list is limited by 21 max donators so it doesn't take up much screen space.
=> fix: make donators list limited

client/src/pages/index.tsx, server/src/routes/feedback.ts
fix: always save active course id
=> fix: do not pass empty courseId to query

.github/workflows/pull_request.yml, client/src/utils/axios.ts, server/src/routes/index.ts, server/src/routes/middlewares.ts
Fixes https://github.com/rolling-scopes/rsschool-app/issues/502
=> fix: Internal Server Error when start the app

server/src/routes/course/index.ts
=> fix: allow to expel mentor for course manager

client/src/pages/course/score.tsx, client/src/services/course.ts, common/types/score/index.ts, server/src/routes/course/score.ts, server/src/services/course.service.ts
Fixes https://github.com/rolling-scopes/rsschool-app/issues/490
=> feat: score page sorting on the server

client/src/domain/interview.ts, client/src/pages/course/student/interviews.tsx, client/src/services/course.ts, common/models/index.ts, common/models/interview.ts, server/src/models/stageInterview.ts, server/src/repositories/interview.ts, server/src/repositories/stageInterview.ts, server/src/repositories/student.ts, server/src/routes/profile/stage-interview-feedback.ts, server/src/services/course.service.ts
Fixes https://github.com/rolling-scopes/rsschool-app/issues/389
Fixes #397
Fixes #408
=> feat: cancel technical screening if student/mentor expelled

client/src/pages/course/score.tsx, server/src/models/student.ts, server/src/schedule.ts, server/src/services/score.service.ts
=> feat: implement #585

client/src/pages/course/student/dashboard.tsx
=> fix: add 'Technical screening' task in completed taks if completed

client/src/pages/course/admin/mentors.tsx
=> feat: Add max students count to the 'Course mentors' page

client/src/components/Profile/ConsentsCard.tsx
=> fix: add link for the rss telegram bot

client/src/pages/course/score.tsx, client/src/utils/queryParams-utils.test.ts, client/src/utils/queryParams-utils.ts, server/src/routes/course/score.ts, server/src/services/score.service.ts
This PR fixes https://github.com/rolling-scopes/rsschool-app/issues/622
=> Apply Location filter to Export CSV functionality

client/src/styles/main.css
=> fix: add style for always showing scrollbar in task select component

client/src/pages/course/student/cross-check-submit.tsx, client/src/styles/main.css
=> fix: add link styling on focus

client/src/components/Forms/Heroes/index.tsx, server/src/services/score.service.ts
1. fix initial request heroes page
2. fix margin for heroes card
This fixes #643
=> fix: fix initial request and card margin

client/src/pages/admin/tasks.tsx
=> fix(655): task json validation

client/src/pages/course/score.tsx
=> feat(score): add total

client/src/pages/course/student/auto-test.tsx
=> feat: add explanations for tasks like codewars and jstask

client/src/pages/registry/student.tsx
=> fix: Gdpr field renders correctly on high resolution displays

client/src/pages/registry/mentor.tsx
=> fix: add automatic course highlighting when using aliases

client/src/components/Dashboard/RepositoryCard.tsx
=> fix: give button for create repo clear naming

client/src/pages/admin/registrations.tsx, client/src/pages/registry/epamlearningjs.tsx, client/src/pages/registry/mentor.tsx, client/src/pages/registry/student.tsx, server/src/models/mentorRegistry.ts, server/src/models/registry.ts, server/src/repositories/mentorRegistry.ts, server/src/routes/registry/index.ts
=> fix: delete the comment field on the registartion page

client/src/components/Dashboard/TasksStatsModal.tsx
=> fix the size of the table with tasks on the student's dashboard

server/src/routes/course/crossCheck/getCrossCheckPairs.ts, server/src/services/taskResults.service.ts
This PR fixes https://github.com/rolling-scopes/rsschool-app/issues/542
=> Fix cross check table

client/src/pages/registry/mentor.tsx
This fixes #730
Three fields are required, but after filling in one of the three fields, this requirement disappears.
=> feat: add the requirement of one mandatory contact for the mentor

client/src/pages/admin/courses.tsx, client/src/pages/course/student/dashboard.tsx, common/models/course.ts, server/src/models/course.ts, server/src/routes/course/repository.ts, server/src/services/repository.service.ts
=> feat(course): add "usePrivateRepositories" flag

client/package-lock.json, client/package.json, client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap
=> chore: update antd

client/src/pages/course/mentor/interview-technical-screening.tsx
=> Fix bugs with interview technical scrining

client/src/pages/course/student/cross-check-review.tsx, client/src/pages/course/student/cross-check-submit.tsx, client/src/services/validators.ts
=> Fix a bug with an invalid link

server/src/models/taskVerification.ts, server/src/schedule.ts, server/src/services/taskVerification.service.ts
=> feat: automatically cancel pending tasks

client/src/components/AdminSider.tsx, client/src/pages/admin/user-group.tsx, client/src/pages/course/admin/users.tsx, client/src/services/course.ts, client/src/services/models.ts, client/src/services/userGroup.ts, common/models/index.ts, common/models/user-group.ts, server/src/models/index.ts, server/src/models/userGroup.ts, server/src/routes/course/index.ts, server/src/routes/course/user.ts, server/src/routes/index.ts, server/src/routes/userGroup/index.ts
=> feat: add users groups

client/src/pages/registry/mentor.tsx
=> fix(730): initial contacts validation

client/src/components/Forms/LocationSelect.tsx, client/src/components/Profile/MainCard.tsx, client/src/components/Profile/__test__/__snapshots__/MainCard.test.tsx.snap, client/src/jest.config.js, client/src/pages/profile/index.tsx
=> fix(795): location editing on profile

client/src/components/Table/columns.tsx
=> Add autofocus to search fields

client/src/next-env.d.ts, server/src/routes/course/index.ts, server/src/routes/course/score/recalculateScore.ts, server/src/services/score.service.ts
=> fix(score): change how we calculate rank

client/src/modules/Score/components/ScoreTable/index.tsx
=> 880: columns visibilty modal behaviour

client/src/pages/course/student/auto-test.tsx, client/src/services/course.ts
=> feat(rsapp test): make attempts number more recognizable

client/src/pages/course/admin/mentors.tsx, client/src/services/course.ts, client/src/styles/main.css, server/src/routes/course/index.ts, server/src/routes/course/mentor.ts, server/src/services/course.service.ts
=> Add the ability to restore the mentor to the course

client/src/pages/course/entityDetails.tsx
=> fix: restored alias for link (#877)

client/src/components/Profile/MentorStatsCard.tsx, client/src/components/Profile/__test__/__snapshots__/MentorStatsCard.test.tsx.snap
=> Fix the bug with with students count in the mentor statistics profile

client/src/pages/course/student/auto-test.tsx
=> fix (autotest): show images for checkbox answers

server/src/routes/opportunities/getResume.ts
https://github.com/rolling-scopes/rsschool-app/issues/945
Fixed source of user's githubId. An incorrect githubId source resulted in the admin or hirer not receiving user information from the server.
=> Fix CV access bug

client/src/pages/gratitude.tsx
=> fix: change badge id

.gitignore, client/src/components/Dashboard/PerformanceChart.tsx
=> Fix rounding on Students Dashboard

server/src/rules/createUser.ts
---
Fixes https://github.com/rolling-scopes/rsschool-app/issues/1026
=> fix(user): github username change

client/src/components/Dashboard/RepositoryCard.tsx, server/package-lock.json, server/package.json, server/src/services/github.service.ts, server/src/services/repository.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1024
=> fix(github): switch to using octokit package and fix REST api usage

client/src/components/Schedule/TableView.tsx, client/src/components/Schedule/UserSettings/TagColor.tsx, client/src/components/Schedule/UserSettings/UserSettings.tsx, client/src/components/Table/renderers.tsx, client/src/pages/course/schedule.tsx, client/src/services/course.ts, client/src/styles/main.css
---
Implementation of #1020:
Added filter for done tasks 
Added info about **max score** and % of the readiness of the task.
=> feat(schedule): add done tasks filter and max score

client/next.config.js, server/src/routes/course/mentors/getMentorsDetailsCsv.ts, server/src/routes/course/score/getScoreCsv.ts
=> fix(csv): export to csv is broken

client/src/components/Forms/ScoreInput.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1023
add decimalSeparator prop for InputNumber.
=> fix: update score input

server/src/services/repository.service.ts
=> fix(github): do no fail if mentor does not exist in Github  anymore

client/src/components/Profile/PublicFeedbackModal.tsx, client/src/components/Profile/__test__/__snapshots__/PublicFeedbackModal.test.tsx.snap, common/models/profile.ts, server/src/routes/profile/public-feedback.ts
=> chore: remove obsolete heroes uri

client/src/components/Profile/ContactsCard.tsx, client/src/components/Profile/__test__/ContactsCard.test.tsx, client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap, common/models/profile.ts, server/src/routes/profile/save.ts, server/src/routes/profile/user-info.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/940
add epam EMAIL prop for profile
=> Add epam email in profile

server/src/migrations/1639418471577-Indicies.ts, server/src/migrations/index.ts, server/src/models/courseTask.ts, server/src/models/student.ts, server/src/models/taskVerification.ts, setup/backup-local.sql
=> Optimize sql

docs/RS APP Platform/rs-app-shedule.md, docs/RS APP Platform/rs-app-tasks.md, docs/RS APP Platform/rs-app.md
Переведены на английский язык rs-app, rs-app-shedule, rs-app-tasks. 
Ссылки на изображения и форматирование сохранены как в исходных md-файлах.
---
=> Documentation update: translate rs-app, rs-app-shedule, rs-app-tasks

.github/workflows/deploy-bumblebee.yaml, docs/RS APP Platform/rs-app-shedule.md, docs/RS APP Platform/rs-app-tasks.md, docs/RS APP Platform/rs-app.md, tools/bumblebee/docker-compose.yml
=> feat: add deploy step for bumblebee

docs/RS APP Platform/rs-app-adding-tests.md, docs/RS APP Platform/rs-app-cross-check-flow.md, docs/RS APP Platform/rs-app-notifications.md, docs/RS APP Platform/rs-app-shedule.md, docs/RS APP Platform/rs-app-tasks.md, docs/RS APP Platform/rs-app-team-allocation.md, docs/RS APP Platform/rs-app-typical-problems.md, docs/RS APP Platform/rs-app.md
Documentation translation
Link: [cross-check](https://docs.rs.school/#/cross-check-flow?id=cross-check), [notifications](https://docs.rs.school/#/notifications), [teams](https://docs.rs.school/#/teams), [issues](https://docs.rs.school/#/rs-app-issues) and [adding tests](https://docs.rs.school/#/rs-app-add-tests) in docs.rs.school
=> docs: translate rs-app-cross-check

.github/workflows/pull_request.yml, nestjs/package-lock.json, nestjs/package.json, nestjs/src/auth/auth-user.model.spec.ts, nestjs/src/auth/auth-user.model.ts, nestjs/src/auth/auth.controller.spec.ts, nestjs/src/auth/auth.service.spec.ts
=> fix(auth): restore supervisor permissions

nestjs/src/app.module.ts, nestjs/src/core/middlewares/index.ts, nestjs/src/core/middlewares/no-cache.middleware.ts
=> fix: add  Cache-Control no-cache header

client/package-lock.json, client/package.json, client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/PermissionsSettingsDrawer.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap, client/src/components/Table/columns.tsx, client/src/modules/Score/data/getColumns.tsx
=> fix(score): reset button

client/src/components/PageLayout.tsx, client/src/components/withSession.tsx, client/src/domain/user.test.tsx, client/src/domain/user.ts, client/src/modules/Home/pages/HomePage/index.tsx, client/src/modules/Mentor/hooks/useMentorStudents.tsx, client/src/modules/Mentor/pages/StudentFeedback/index.tsx, client/src/modules/Mentor/pages/Students/index.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/course/mentor/expel-student.tsx
=> fix(ui): various fixes

nestjs/src/auth/course.guard.ts, nestjs/src/auth/strategies/jwt.strategy.ts, nestjs/src/core/middlewares/no-cache.middleware.ts, nestjs/src/courses/courses.controller.ts, nestjs/src/courses/interviews/interviews.controller.ts, nestjs/src/courses/interviews/interviews.service.ts, nestjs/src/courses/tasks/course-tasks.controller.ts, nestjs/src/courses/tasks/course-tasks.service.ts, nestjs/src/disciplines/disciplines.controller.ts, nestjs/src/migrations.ts, nestjs/tsconfig.json
=> chore: add stricter rules to tsconfig.json

renovate.json
=> Deps update

client/src/modules/Home/pages/HomePage/index.tsx, client/src/modules/Registry/pages/Student/index.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1151
1) Changed label for location in student registry form
Before changes
After changes
es
2) Fixed bug with empty list appearing on homepage for newly registering users
Before changes:
After changes
=> refactor: change registration label & fix minor bug

client/src/components/PageLayout.tsx, client/src/domain/user.ts, client/src/modules/Mentor/hooks/useMentorStudents.tsx, client/src/modules/Mentor/pages/StudentFeedback/index.tsx, client/src/modules/Mentor/pages/Students/index.tsx, client/src/modules/Score/data/getColumns.tsx, client/src/pages/course/mentor/expel-student.tsx, client/src/services/routes.ts
=> fix(feedback): improve feedback form

client/src/data/interviews/corejs1.ts
=> fix: change link

client/src/components/Schedule/FormEntity.tsx, client/src/components/Schedule/TableView.tsx, client/src/components/Schedule/model.ts, client/src/components/Table/renderers.tsx, client/src/pages/course/schedule.tsx, client/src/styles/main.css
---
#1067 
- remove `place` column
- remove `url` column 
- remove 'task' popup
- update 'score'. Fix issue with null.
- highlight current week 
=> Schedule refactoring

client/src/pages/course/_middleware.ts
=> fix truncate redirect path to pathname

client/src/data/interviews/corejs1.ts, client/src/data/interviews/types.ts, client/src/modules/Interviews/pages/InterviewFeedback/index.tsx
=> feat(interview): add interview points description

client/src/data/interviews/corejs1.ts, client/src/data/interviews/corejs2.ts, client/src/data/interviews/index.ts
=> feat(interview): create corejs2 template

client/src/modules/Home/components/HomeSummary/index.tsx, nestjs/src/alerts/alerts.controller.ts, nestjs/src/auth/auth-user.model.ts, nestjs/src/auth/role.decorator.ts, nestjs/src/auth/role.guard.ts, nestjs/src/courses/courses.controller.ts, nestjs/src/disciplines/disciplines.controller.ts, nestjs/src/notifications/notifications.controller.ts, nestjs/src/registry/registry.controller.ts, server/src/config.ts
Refactors guard to combine possible roles in single guard.
=> feat: role guard to accept app and course roles

nestjs/src/auth/auth-user.model.ts, nestjs/src/auth/strategies/basic.strategy.ts, nestjs/src/notifications/email-template.ts, nestjs/src/notifications/notifications.service.ts, nestjs/src/users/users.notifications.service.ts
- add email template
-  update basic auth to create new user
=> Auth strategy

.github/workflows/nextjs_bundle_analysis.yml, .github/workflows/pull_request.yml, .github/workflows/renovate.yml, CONTRIBUTING.md, README.md, client/next.config.js
=> docs: update readme

server/src/models/session.ts, server/src/routes/middlewares.ts
=> fix: auth for server

client/src/components/Forms/Heroes/index.tsx
=> fix(heroes): GithubId -> Github Username

nestjs/src/users/users.notifications.controller.ts
=> fix(notifications): find connection api hangs due to body attribute

client/src/utils/text-utils.ts
---
Fixes #1199 
Update regexp
=> fix: github id match

server/src/repositories/courseTask.repository.ts, server/src/routes/profile/student-stats.ts
---
This fixes #1181 and fixes #1177
Dashboard:
Score:
Schedule:
Profile:
=> fix: interviews score displaying

server/src/repositories/courseTask.repository.ts
=> fix: schedule

nestjs/src/core/templates/index.ts, nestjs/src/main.ts
=> feat(notifications): add truncate helper for template

.github/workflows/deploy.yaml, .github/workflows/pull_request.yml, client/next.config.prod.js, client/src/modules/Registry/hooks/useStudentsCourseData.tsx, client/src/modules/Registry/pages/Mentor/index.tsx, client/src/services/cdn.ts, client/src/services/courses.ts
=> feat: add cdn service

.github/workflows/pull_request.yml, client/src/components/Header.tsx, client/src/components/SolidarityUkraine.tsx, client/src/modules/Registry/pages/Mentor/index.tsx, client/src/modules/Registry/pages/Student/index.tsx, client/src/services/cdn.ts, nestjs/src/auth/strategies/dev.strategy.ts
=> feat: add solidarity component

client/src/__tests__/ProfilePage.test.tsx, client/src/__tests__/__snapshots__/ProfilePage.test.tsx.snap, client/src/components/Profile/CoreJsIviewsCard.tsx, client/src/components/Profile/CoreJsIviewsModal.tsx, client/src/components/Profile/__test__/CoreJsIviewsCard.test.tsx, client/src/components/Profile/__test__/CoreJsIviewsModal.test.tsx, client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap, client/src/pages/profile/index.tsx, nestjs/src/notifications/notifications.service.ts
=> fix: coreJs interviews in students profile

client/src/modules/Notifications/components/NotificationSettingsModal.tsx
=> refactor(notifications): make the modal tabbular

client/src/pages/course/student/auto-test.tsx, client/src/pages/epamlearningjs.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1264
Due to the Node.js auto-check runtime update Changed Node.js versions in RS App
=> chore: update node version disclaimers

client/src/domain/interview.ts, server/src/services/course.service.ts
---
Fixes #1175 
Dashboard:
Interviews:
=> fix: corejs score in dashboard and interviews

server/src/services/course.service.ts
=> fix: get student summary route failing

client/src/modules/StudentDashboard/components/MainStatsCard.tsx
=> fix: max course score on dashboard

client/src/components/Schedule/TableView.tsx
=> Remove column 'Duration' im schedule

client/src/modules/Home/components/CourseSelector/index.tsx, client/src/modules/Home/pages/HomePage/index.tsx
=> feat(home): update course selector

client/src/pages/course/admin/cross-check-table.tsx, client/src/pages/course/admin/mentors.tsx
=> fix: change columns width

client/src/modules/Notifications/components/NotificationSettingsModal.tsx, nestjs/src/app.module.ts, nestjs/src/courses/courses.service.ts, nestjs/src/courses/tasks/course-tasks.service.ts, nestjs/src/notifications/dto/notification.dto.ts, nestjs/src/notifications/dto/update-notification.dto.ts, nestjs/src/notifications/notificationIds.ts, nestjs/src/schedule/schedule.controller.ts, nestjs/src/schedule/schedule.module.ts, nestjs/src/schedule/schedule.service.ts, server/src/routes/course/crossCheck/createResult.ts, server/src/routes/course/interviews.ts, server/src/routes/course/score/createSingleScore.ts, server/src/services/notification.service.ts
- Adds endpoint for checking schedule changes for course
- removes scope from notification
=> feat(notifications): schedule changes

server/src/repositories/feedback.repository.ts
---
No issue
Route `api/feedback/gratitude` returns wrong feedback count. Count is grouped by user, so if we make a search by GitHub - we always get `count = 1` for that user, even if he has more feedback. It also causes a problem with pagination (always one page).
Also search by name doesn’t allow search by full name.
After fix:
=> fix: heroes page feedback count, full name search

client/src/components/Schedule/EditableCell.tsx, client/src/components/Schedule/model.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1067
=> Remove duration from setting column

docs/_sidebar.md, docs/code-of-conduct.md, docs/platform/tasks.md
=> feat: add code of conduct to docs

client/src/components/Header.tsx
=> fix: change help button behavior

client/src/pages/admin/events.tsx
=> feat: add search by name for events

nestjs/src/courses/tasks/tasks.service.ts, nestjs/src/schedule/schedule.service.ts
filters non active students for notifications
=> fix(notification): filter expelled students

client/src/modules/Notifications/components/Consents.tsx, client/src/modules/Notifications/components/NotificationSettingsModal.tsx, client/src/modules/Notifications/components/NotificationsUserSettingsTable.tsx, client/src/modules/Notifications/pages/UserNotificationsSettingsPage.tsx, client/src/modules/Notifications/services/notifications.ts, nestjs/src/notifications/notifications.service.ts, nestjs/src/users-notifications/dto/notification-user-connections.dto.ts, nestjs/src/users-notifications/users.notifications.controller.ts, server/src/migrations/1650652882300-DiscordChannel.ts, server/src/migrations/index.ts, server/src/models/notificationChannel.ts, server/src/models/notificationChannelSettings.ts
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/1345)
Adds new `discord` channel
=> feat(notifications): add discord channel

nestjs/src/schedule/schedule.service.ts
schedule notification is sent to course manager as well
=> feat(notifications): schedule manager notifications

nestjs/src/courses/tasks/tasks.controller.ts, nestjs/src/schedule/schedule.controller.ts
https://github.com/rolling-scopes/rsschool-app/issues/1402
actions for schedule & tasks are triggered outside. to not block caller, we execute only search in synchronous way and actual notification processing in async. this way caller will get response and not wait for notifications to be processed
=> fix(notifications): handle schedule&tasks notifications in async way

docs/platform/cross-check-flow.md
---
_Fixed critical mistake in cross-check docs_
=> fix: fix appeal criteria

client/src/modules/StudentDashboard/components/MainStatsCard.tsx, client/src/modules/StudentDashboard/components/PerformanceChart.tsx, client/src/pages/course/student/dashboard.tsx
---
[issue#1375](https://github.com/rolling-scopes/rsschool-app/issues/1375)
[Demonstration](https://youtu.be/swYuZHOEtok)
Figma [file](https://www.figma.com/file/D3O7GJzjlG38YLh8FpmetI/RS-Design?node-id=121%3A11246)
- Haven't figured out how to set space (1px) between range and tick line as it shown on design;
- Haven't figured out how to set only 3 tick lines as it shown on design;
- Have used …
=> feat: redesign dashboard's main stats widget

server/src/routes/profile/student-stats.ts
=> Fix bug with dashboard

client/src/components/Forms/CourseTaskSelect.tsx, client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx, client/src/modules/StudentDashboard/components/TasksStatsCard.tsx, client/src/modules/StudentDashboard/components/TasksStatsModal.tsx, server/src/routes/course/crossCheck/createResult.ts, server/src/routes/course/score/createSingleScore.ts, server/src/services/tasks.service.ts
https://github.com/rolling-scopes/rsschool-app/issues/1395
Adds link to task grade notification pointing to respective page in the app
=> feat(notifications): add task result link to rs app

client/src/components/Table/renderers.tsx, client/src/modules/Notifications/components/NotificationsUserSettingsTable.tsx, client/src/modules/Notifications/pages/UserNotificationsSettingsPage.tsx, nestjs/src/users-notifications/users.notifications.service.ts
Reverts rolling-scopes/rsschool-app#1428
=> Revert "feat(notifications): turn on notifications by default"

nestjs/src/courses/courses.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1434
=> fix(notifications): send schedule update for event changes

client/src/components/Table/renderers.tsx, client/src/modules/Notifications/components/NotificationsUserSettingsTable.tsx, client/src/modules/Notifications/pages/UserNotificationsSettingsPage.tsx, nestjs/src/notifications/notifications.service.ts, nestjs/src/users-notifications/users.notifications.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1419
=> feat(notifications): turn on notifications by default

nestjs/src/opportunities/opportunities.service.ts, nestjs/src/profile/dto/profile.dto.ts, nestjs/src/profile/profile.controller.ts, nestjs/src/profile/profile.service.ts, server/src/models/resume.ts
=> fix: profile api response

client/src/modules/Score/components/ScoreTable/index.tsx, client/src/modules/Score/data/getColumns.tsx
---
[issue#1420](https://github.com/rolling-scopes/rsschool-app/issues/1420)
=> fix: score table bugs

client/src/modules/Score/components/ScoreTable/index.tsx, client/src/modules/Score/data/getColumns.tsx
Reverts rolling-scopes/rsschool-app#1452
=> Revert "fix: score table bugs"

client/src/modules/Opportunities/components/CoursesSection.tsx, client/src/modules/Opportunities/components/PublicLink.tsx, client/src/modules/Opportunities/components/ViewCV.tsx, docs/platform/cv.md, nestjs/src/opportunities/opportunities.service.ts
=> fix: courses visibility

server/src/routes/course/score/getScoreCsv.ts, server/src/services/score/score.service.ts
---
Fixes https://github.com/rolling-scopes/rsschool-app/issues/1467
=> fix: add certificate data to csv

client/src/pages/course/schedule.tsx
---
This fixes #1480
This fixes #1458 
=> fix: hide old events using endDate instead of startDate

client/package-lock.json, client/package.json, client/src/components/CrossCheckComments.tsx, client/src/components/__tests__/__snapshots__/CrossCheckComments.test.tsx.snap
:scream:   Accidentally scrolling through the discord, I saw this screenshot  in one of the chats :anguished::, 
<details>
<summary>Screen</summary>
</details>
I realized that I had missed the obvious thing - to add a new component to submit part of cross-check. I am correcting myself. Example on test base:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
:cold_sweat::cold_sweat::cold_sweat:
---
=> fix: markdown for submit section

server/src/routes/course/index.ts, server/src/routes/guards.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1460
Cross-check didn't work properly because of inapropriate auth mechanism for `distribution` and `completion` endpoints. I implemented auth middleware that covers all the cases of authorized access and doesn't allow unauthorized users get access to Cross-Check functionality
=> Fix: Cross-Check authorization

client/src/components/StudentSearch.tsx, client/src/components/UserSearch.tsx, client/src/pages/course/mentor/confirm.tsx, client/src/services/course.ts, server/src/repositories/student.repository.ts, server/src/routes/course/students.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1494
=> Disable selection of students who already have a mentor

nestjs/src/schedule/dto/check-schedule-changes.ts, nestjs/src/schedule/schedule.controller.ts, nestjs/src/schedule/schedule.service.ts
Moves schedule check time to dto object
=> refactor: move schedule check time to caller dto

client/src/pages/course/mentor/submit-review.tsx
---
Fixes https://github.com/rolling-scopes/rsschool-app/issues/1453
=> fix: remove comment from submit review

nestjs/src/courses/courseTasks/course-tasks.service.ts
=> fix: order tasks by studentEndDate + name

client/src/components/Schedule/SettingsDrawer/SettingsDrawer.tsx, client/src/components/Schedule/SettingsDrawer/TimeZone.tsx, client/src/components/Schedule/useScheduleSettings.ts
=> fix: remove firstDayOfTheWeek setting

client/src/components/Schedule/SettingsDrawer/TimeZone.tsx, client/src/configs/timezones.ts
=> fix: show all the timezones in the schedule

server/src/routes/course/taskVerification.ts
---
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/1500)
=> fix:  change test result message

client/src/components/Sider/AdminSider.tsx
=> feat: save colapsed sider status in local storage

client/src/components/Forms/MarkdownInput.tsx
… result
---
https://github.com/rolling-scopes/rsschool-app/issues/1513
=> Fix bug with showing mardown after submitting cross check review result

client/src/pages/course/mentor/interview-technical-screening.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1548
=> Fix reset values after changing anything after page reload

client/src/pages/course/admin/stage-interviews.tsx, client/src/services/course.ts, server/src/repositories/interview.repository.ts, server/src/repositories/stageInterview.repository.ts, server/src/routes/course/stageInterview/createInterviews.ts, server/src/rules/interviews.ts
=> fix: remove keepReserve and do fixes for distribution

server/src/models/notification.ts, server/src/repositories/student.repository.ts, server/src/routes/course/student.ts, server/src/rules/mentors.ts, server/src/services/mentor.service.ts, server/src/services/notification.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1554
=> feat(notifications): send mentor assinged notification

nestjs/src/core/subscribers/base-subscriber.ts, nestjs/src/core/subscribers/course-event.subscriber.ts, nestjs/src/core/subscribers/course-task.subscriber.ts, nestjs/src/core/templates/index.ts, nestjs/src/courses/course-events/course-events.service.ts, nestjs/src/courses/course-tasks/course-tasks.service.ts, nestjs/src/courses/courses.service.ts, nestjs/src/notifications/email-template.ts, nestjs/src/ormconfig.ts, nestjs/src/schedule/schedule.module.ts, nestjs/src/schedule/schedule.service.ts, server/src/migrations/1656326258991-History.ts, server/src/migrations/index.ts, server/src/models/history.ts, server/src/models/index.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1406
=> Schedule changes details

server/src/routes/course/index.ts
Reverts rolling-scopes/rsschool-app#1559
=> Revert "fix: add permission validation for mentor endpoint"

server/src/repositories/stageInterview.repository.ts, server/src/routes/course/index.ts, server/src/routes/course/stageInterview/cancelInterview.ts, server/src/routes/course/stageInterview/index.ts
=> fix(1587): cancel interview but not delete

server/src/repositories/student.repository.ts, server/src/routes/course/student.ts
=> fix: student unassign from mentor

setup/nginx/nginx.conf
=> fix: update nginx config

client/src/pages/course/student/auto-test.tsx
---
Fixed Node.js version in warning 14 => 16
=> Fix version of Node.js for autotests

tools/bumblebee/package-lock.json, tools/bumblebee/package.json
=> feat: update forever for bumblebee

client/src/components/Schedule/SettingsPanel/ManageCsvButtons.tsx
=> fix: change import and export csv icons

server/src/services/distribution/__tests__/crossMentor.test.ts, server/src/services/distribution/crossMentorDistribution.service.ts
=> fix: update distribution rules for cross mentor

client/src/pages/course/student/cross-check-review.tsx, client/src/pages/course/student/dashboard.tsx
---
Изменены margin'ы на страницах `dashboard` и `cross-check-review`
<details>
<summary>(IMG)</summary>
</details>
=> refactor: change margin of pages

client/src/components/Footer/Help.tsx
---
После перехода по ссылке `Report a bug` в футере,  не отображается шаблон сообщения.
=> fix: change footer link

tools/bumblebee/package-lock.json, tools/bumblebee/package.json
=> fix: pin bumblebee dependencies

client/package-lock.json, client/package.json, client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/CommonCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/MainCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/MentorStatsCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/PermissionsSettingsDrawer.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/ProfileSettingsDrawer.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/PublicFeedbackCard.test.tsx.snap, client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap, client/src/modules/StudentDashboard/components/TasksChart.tsx
=> chore: update antd packages

nestjs/src/app.module.ts, nestjs/src/cloud-api/cloud-api.module.ts, nestjs/src/cloud-api/cloud-api.service.ts, nestjs/src/core/filters/entity-not-found.filter.ts, nestjs/src/core/filters/index.ts, nestjs/src/core/filters/unhandled-exceptions.filter.ts, nestjs/src/setup.ts, server/src/logger.ts, server/src/routes/logging.ts
=> feat: send error to queue

nestjs/src/activity/activity.controller.ts, nestjs/src/alerts/alerts.service.ts, nestjs/src/profile/profile.service.ts, nestjs/src/users/users.service.ts
=> perf: optimize queries

client/src/modules/Schedule/components/SettingsDrawer/SettingsDrawer.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1672)
=> fix: change triggers for Schedule settings tooltip

client/src/components/Icons/CourseIcon.tsx, client/src/modules/Home/components/CourseSelector/index.tsx, client/src/modules/Registry/components/MentorRegistrationGeneral/index.tsx, client/src/modules/Registry/pages/Student/index.tsx
---
Добавил иконки курсов на странице регистрации
=> feat: add course icons to registration page

client/src/components/Table/renderers.tsx, client/src/pages/admin/courses.tsx
=> fix(course): set start/end date as start of the day in UTC

nestjs/src/courses/course-schedule/course-schedule.service.ts
=> fix(schedule): show task taskOwner as organizer

client/src/modules/Registry/pages/Student/index.tsx, client/src/pages/admin/registrations.tsx, client/src/services/cdn.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1706
For now it's just fix of visual appearance of missing discipline + take courses from `nestjs` API instead of `server` API - in this case course <=> discipline relation resolved correctly
=> Fix: display missing discipline correctly

client/src/pages/course/student/auto-test.tsx, docs/platform/tasks.md
---
This fixes #1544
Depends on [https://github.com/rolling-scopes-school/rsschool-app-private/pull/33/files](https://github.com/rolling-scopes-school/rsschool-app-private/pull/33/files)
=> fix: don't allow submit any codewars username

docs/platform/tasks.md
=> docs: specify how to update username at Codewars

client/src/modules/Registry/pages/Student/index.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1732
Updated text of tooltip on student registration page
=> Update name tooltip on registration page

server/src/routes/course/score/getScoreCsv.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1746
Previously only users with roles `admin` or `hirer` were eligible to see course certificate presence. Now course managers can see certificate presence in corresponding course's score export too.
=> Show certificate presence for course manager

client/src/pages/course/mentor/confirm.tsx, client/src/services/mentorRegistry.ts, server/src/routes/registry/index.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1722
=> Add page for unselected mentors

CONTRIBUTING.md, client/src/api/api.ts, nestjs/src/courses/course-schedule/dto/course-schedule-item.dto.ts, nestjs/src/spec.json
=> fix: dto types

nestjs/src/courses/score/score.service.ts
=> fix(score): 'Active Students Only' switch always show active

client/src/components/CommentModal.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1758
Before you were able to expel student with empty comment  
Now validation works correctly and expel is prevented  
=> Restore broken validation on expel comment

client/src/components/BadReview/BadReviewControllers.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1761)
=> fix: add onCancel for modals in cross-check table page

client/src/api/api.ts, client/src/modules/Schedule/components/ManageEventModalForm/ManageEventForm.tsx, client/src/pages/course/admin/events.tsx, client/src/services/course.ts, nestjs/src/courses/course-events/dto/course-event.dto.ts, nestjs/src/courses/course-events/dto/create-course-event.dto.ts, nestjs/src/courses/course-events/dto/update-course-event.dto.ts, nestjs/src/courses/course-schedule/course-schedule.service.ts, nestjs/src/spec.json, server/src/migrations/1664183799115-CourseEvent.ts, server/src/migrations/index.ts, server/src/models/courseEvent.ts
---
[_issue_](https://github.com/rolling-scopes/rsschool-app/issues/1478)
=> feat: add end date for course event

server/src/services/repository.service.ts
---
[link](https://github.com/rolling-scopes/rsschool-app/issues/1763)
private repositories for students will be created based on the template
https://github.com/rolling-scopes-school/template-repo
=> feat: change the process of creating repositories

server/src/services/repository.service.ts
Reverts rolling-scopes/rsschool-app#1764
=> Revert "feat: change the process of creating repositories"

client/src/modules/Opportunities/components/ExpirationTooltip/index.test.tsx, client/src/modules/Opportunities/components/ExpirationTooltip/index.tsx
---
Blocked renew modal show in public mode
=> Block renew modal in public mode

server/src/repositories/student.repository.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1775
=> fix: fix student deletion

nestjs/src/auth/auth-user.model.spec.ts, nestjs/src/auth/auth-user.model.ts, server/src/routes/middlewares.ts
=> feat: use undefined instead of null

client/src/components/Student/CertificateCriteria.tsx, client/src/components/Student/ExpelCriteria.tsx, client/src/modules/InterviewQuestions/components/Modals/CategoryModalForm/index.tsx, client/src/modules/InterviewQuestions/components/Modals/QuestionModalForm/index.tsx, client/src/modules/Registry/components/MentorRegistrationGeneral/index.tsx, client/src/modules/Registry/components/MentorRegistrationMentorship/index.tsx, client/src/pages/admin/mentor-registry.tsx
https://github.com/rolling-scopes/rsschool-app/issues/1778
Added missing property
=> fix: enable filter in selects

client/src/pages/course/student/auto-test.tsx
=> fix: spelling

server/src/repositories/student.repository.ts
https://github.com/rolling-scopes/rsschool-app/issues/1745
Interview score was not queried.
=> fix(certificates): generation of certificate having interview as a criteria

client/src/modules/Registry/components/MentorStepAbout/index.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1739
Changed Mentorship page according to requirements in issue
=> Update mentorship text

client/src/api/api.ts, client/src/modules/Schedule/components/TableView/TableView.test.tsx, client/src/modules/Schedule/components/TableView/TableView.tsx, nestjs/src/courses/course-schedule/dto/course-schedule-item.dto.ts, nestjs/src/spec.json
---
#1801 
- Fix extra rows when switch tabs
=> fix(schedule): use course id for unique key

client/src/modules/Opportunities/components/EditCv/form-validation.ts
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1809)
=> fix(opportunities): do phone and email not required fields

client/src/pages/course/student/auto-test.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1803)
=> fix(auto-test): add error messages for 401 error

client/package-lock.json, client/package.json, client/src/api/api.ts, client/src/index.d.ts, client/src/modules/Mentor/components/TaskSolutionsTable/TaskSolutionsTable.test.tsx, client/src/modules/Mentor/components/TaskSolutionsTable/TaskSolutionsTable.tsx, client/src/modules/Mentor/components/TaskSolutionsTable/renderers.tsx, client/src/modules/Mentor/components/TaskStatusTabs/TaskStatusTabs.test.tsx, client/src/modules/Mentor/components/TaskStatusTabs/TaskStatusTabs.tsx, client/src/modules/Mentor/components/TaskStatusTabs/index.ts, client/src/modules/Mentor/components/TaskStatusTabs/renderers.tsx, client/src/modules/Mentor/constants.ts, client/src/pages/course/mentor/dashboard.tsx, client/src/setupJest.ts, nestjs/src/courses/mentors/dto/mentor-dashboard.dto.ts, nestjs/src/courses/mentors/mentors.service.ts, nestjs/src/spec.json
---
#1586 
* Show status tabs for task
* Add mobile view for table
* Show desired deadline for review
* Add tests for new functionality
=> feat(mentor-dashboard): status tabs and desired deadline

server/src/services/course.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1799
=> fix: cross-check end date on course copying

client/src/modules/StudentDashboard/components/TasksChart.tsx, client/src/modules/StudentDashboard/components/TasksStatsCard.tsx, client/src/pages/course/student/dashboard.tsx
https://github.com/rolling-scopes/rsschool-app/issues/1838
- removes dynamic layout for char - breaks antd re-render
- removes achieved tasks
- decreases chart height
=> fix: layout for student dashboard. chart fixes

server/src/services/repository.service.ts
=> fix: remove gitignore params

server/src/services/repository.service.ts
=> fix: add owner for private repo

client/src/api/api.ts, client/src/components/Table/renderers.tsx, client/src/modules/Schedule/components/TableView/TableView.test.tsx, client/src/modules/Schedule/components/TableView/TableView.tsx, client/src/modules/Schedule/components/TableView/renderers.tsx, client/src/modules/StudentDashboard/components/CommonDashboardCard.tsx, client/src/modules/StudentDashboard/components/NextEventCard.tsx, client/src/modules/StudentDashboard/components/NextEventCard/NextEventCard.test.tsx, client/src/modules/StudentDashboard/components/NextEventCard/NextEventCard.tsx, client/src/modules/StudentDashboard/components/NextEventCard/index.tsx, client/src/modules/StudentDashboard/components/NextEventCard/renderers.tsx, client/src/modules/StudentDashboard/components/index.ts, client/src/modules/StudentDashboard/components/renderers.tsx, client/src/pages/course/student/dashboard.tsx, nestjs/src/spec.json
---
#1848 
- Show course schedule available tasks instead of course events
- Move table renderers (task, date) form Schedule component to Table 
- Rearrange cards order on Student Dashboard
=> feat(student-dashboard): available tasks

client/package-lock.json, client/package.json, package-lock.json, package.json
* [х] I followed naming convention rules
---
- [х] Other
add needed libraries in client directory
- [х] Database migration is added or not needed
- [х] Documentation is updated/provided or not needed
=> fix: add test libraries

client/src/pages/course/student/cross-check-review.tsx, client/src/services/course.ts
* [х] I followed naming convention rules
---
- [х] Bug fix
[#1873 ](url)
- [х] Database migration is added or not needed
- [х] Documentation is updated/provided or not needed
=> fix: issue 1873 update review without criteria

client/src/modules/StudentDashboard/components/RepositoryCard.tsx
---
[_issue_](https://github.com/rolling-scopes/rsschool-app/issues/1850)
=> fix: fix type Fix Repository button

client/src/modules/AutoTest/components/Coding/Coding.test.tsx, client/src/modules/AutoTest/components/Coding/Coding.tsx, client/src/modules/AutoTest/components/Exercise/Exercise.tsx, client/src/modules/AutoTest/components/SelfEducation/SelfEducation.tsx, client/src/modules/AutoTest/components/StatusTabs/StatusTabs.test.tsx, client/src/modules/AutoTest/components/StatusTabs/StatusTabs.tsx, client/src/modules/AutoTest/components/StatusTabs/index.ts, client/src/modules/AutoTest/components/StatusTabs/renderers.tsx, client/src/modules/AutoTest/components/TaskCard/TaskCard.test.tsx, client/src/modules/AutoTest/components/TaskCard/TaskCard.tsx, client/src/modules/AutoTest/components/TaskDeadlineDate/TaskDeadlineDate.test.tsx, client/src/modules/AutoTest/components/TaskDeadlineDate/TaskDeadlineDate.tsx, client/src/modules/AutoTest/components/TaskDescription/TaskDescription.tsx, client/src/modules/AutoTest/components/VerificationInformation/VerificationInformation.tsx, client/src/modules/AutoTest/components/VerificationsTable/renderers.tsx, client/src/modules/AutoTest/components/index.tsx, client/src/modules/AutoTest/hooks/useAttemptsMessage/useAttemptsMessage.test.ts, client/src/modules/AutoTest/hooks/useAttemptsMessage/useAttemptsMessage.ts, client/src/modules/AutoTest/hooks/useCourseTaskSubmit/useCourseTaskSubmit.test.ts, client/src/modules/AutoTest/hooks/useCourseTaskSubmit/useCourseTaskSubmit.ts, client/src/modules/AutoTest/pages/AutoTests/AutoTests.tsx, client/src/modules/AutoTest/types.ts, client/src/modules/AutoTest/utils/map.ts
=> feat(auto-test): status tabs

client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx
=> feat: add cross-check duration validation

client/src/modules/AutoTest/utils/map.ts
=> fix(auto-test): tasks status

client/src/components/CrossCheck/CrossCheckHistory.tsx, client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx, client/src/modules/CrossCheck/components/SolutionReview/MessageSendingPanel/MessageSendingPanel.tsx, client/src/modules/CrossCheck/components/SolutionReview/SolutionReview.tsx, client/src/services/course.ts, server/src/services/taskResults.service.ts
---
- feat: add review date
- feat: add message preview
=> feat(cross-check): add message preview

client/src/modules/AutoTest/components/Coding/Coding.tsx, client/src/modules/AutoTest/components/Exercise/Exercise.tsx, client/src/modules/AutoTest/components/TaskDescription/TaskDescription.tsx, client/src/modules/AutoTest/components/VerificationInformation/VerificationInformation.tsx, client/src/modules/AutoTest/components/VerificationsTable/renderers.tsx, client/src/modules/AutoTest/hooks/useCourseTaskVerifications/useCourseTaskVerifications.ts, client/src/modules/AutoTest/pages/AutoTests/AutoTests.tsx, client/src/modules/AutoTest/pages/Task/Task.tsx, client/src/pages/course/student/new-auto-test/index.tsx
---
#1712 
New auto-test functionality:
1. Fix: do not show future tasks
2. Add "Refresh" button on task page
3. Small UI improvements
=> fix(auto-test): hide future tasks

nestjs/src/courses/course-schedule/course-schedule.service.ts, server/src/services/course.service.ts
=> fix: shift event endTime

client/src/data/interviews/corejs1.ts
=> feat: update corejs1 template

client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.test.tsx, client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.tsx, client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.test.tsx, client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.tsx, nestjs/src/courses/course-schedule/course-icalendar.service.ts
---
#1865 
Each iCal event should have uniq id but we have a case when Cross-check task has 2 events with the same id
=> feat: generate unique id for each iCal event

client/src/modules/Home/data/links.tsx
---
#1712 
- Make new Auto-test page available from menu
- Old page as backup is still available under /auto-test URL
=> feat(auto-test): enable new auto-test page

client/src/modules/Home/components/CourseSelector/index.tsx
=> feat: add sorting by course activity

client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx
=> fix: correct the text for the cross-check endDate

client/src/components/CopyToClipboardButton.tsx, client/src/pages/admin/mentor-registry.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1920)
=> feat: add resend button for mentor registry page

server/src/repositories/stageInterview.repository.ts
=> fix(stage-interview): ignore disabled interviews

client/src/modules/Mentor/components/Instructions/constants.ts, nestjs/src/courses/mentors/mentors.service.ts
---
1. Fix URLs to docs on instruction page
2. Fix result score: 0 should be considered as result
=> fix(mentor-dashboard): result score as 0

client/src/api/api.ts, client/src/modules/CourseManagement/components/CourseEventModal/index.tsx, client/src/modules/StudentDashboard/components/AvailableReviewCard/AvailableReviewCard.test.tsx, client/src/modules/StudentDashboard/components/AvailableReviewCard/AvailableReviewCard.tsx, client/src/modules/StudentDashboard/components/AvailableReviewCard/index.ts, client/src/modules/StudentDashboard/components/index.ts, client/src/pages/course/student/dashboard.tsx, nestjs/src/courses/course-tasks/course-tasks.service.ts, nestjs/src/courses/courses.module.ts, nestjs/src/courses/cross-checks/course-cross-checks.controller.ts, nestjs/src/courses/cross-checks/course-cross-checks.service.ts, nestjs/src/courses/cross-checks/dto/available-review-stats.dto.ts, nestjs/src/courses/cross-checks/dto/check-tasks-pairs.dto.ts, nestjs/src/courses/cross-checks/dto/index.ts, nestjs/src/courses/cross-checks/index.ts, nestjs/src/spec.json
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1849)
=> feat (Dashboard): add widget Cross-check Review

nestjs/src/courses/course-tasks/course-tasks.service.ts, nestjs/src/cross-check/cross-check.service.ts
=> fix: cross-check not available for disabled tasks

client/src/modules/Teams/components/StudentsWithoutTeamSection/StudentsWithoutTeamSection.tsx, client/src/modules/Teams/components/TeamsSection/TeamsSection.tsx
=> fix: query params order

client/src/api/api.ts, client/src/modules/Home/data/links.tsx, client/src/modules/StudentDashboard/components/AvailableReviewCard/AvailableReviewCard.test.tsx, client/src/modules/StudentDashboard/components/AvailableReviewCard/AvailableReviewCard.tsx, client/src/modules/Teams/Pages/Teams.tsx, client/src/modules/Teams/components/MyTeamSection/MyTeamSection.tsx, client/src/modules/Teams/components/TeamModal/TeamModal.tsx, client/src/modules/Teams/hooks/index.ts, client/src/modules/Teams/hooks/useModal/useModal.test.tsx, client/src/modules/Teams/hooks/useModal/useModal.tsx, nestjs/src/courses/students/students.service.ts, nestjs/src/courses/team-distribution/dto/create-team.dto.ts, nestjs/src/courses/team-distribution/dto/join-team.dto.ts, nestjs/src/courses/team-distribution/team.controller.ts, nestjs/src/spec.json
=> feat: create team flow for admin

client/src/api/api.ts, client/src/components/MentorOptions.tsx, client/src/modules/Mentor/pages/Interviews/components/InterviewDetails.tsx, client/src/modules/Mentor/pages/Interviews/components/MentorPreferencesModal.tsx, client/src/modules/Mentor/pages/Interviews/components/RegistrationNotice.test.tsx, client/src/modules/Mentor/pages/Interviews/components/RegistrationNotice.tsx, client/src/modules/Mentor/pages/Interviews/index.tsx, client/src/pages/course/mentor/confirm.tsx, common/enums/mentor/index.ts, nestjs/src/courses/mentors/dto/mentor-options.dto.ts, nestjs/src/courses/mentors/mentors.controller.ts, nestjs/src/courses/mentors/mentors.service.ts, nestjs/src/spec.json
-  [x] New feature
https://github.com/rolling-scopes/rsschool-app/issues/1815
Adds ability to edit mentor options on interview page
=> feat: interview mentor options submission

client/src/pages/course/admin/stage-interviews.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1965)
=> fix: add confirmation for create technical screening button

nestjs/src/courses/course-events/course-events.controller.ts, nestjs/src/courses/course-tasks/course-tasks.controller.ts, nestjs/src/courses/cross-checks/course-cross-checks.controller.ts
=> fix: cross-check pairs visibility

client/src/data/interviews/corejs2.ts
=> feat: update interview template

client/src/pages/course/student/cross-check-review.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1964)_
=> feat: add warning when submit cross-check review with score 0 points

client/src/pages/course/student/cross-check-review.tsx
=> fix: fix cross-check submit 0

client/src/modules/Home/hooks/useActiveCourse.test.tsx, client/src/pages/course/student/cross-check-review.tsx
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1952)
=> fix: clear cross-check review history when task changed

server/src/migrations/1674755854609-Resume.ts, server/src/migrations/index.ts, server/src/models/resume.ts, setup/backup-local.sql
=> feat: resume should have userId always

.github/workflows/pull_request.yml, client/.eslintrc.js, client/package-lock.json, client/package.json, client/src/api/api.ts, client/src/components/BadReview/BadReviewControllers.tsx, client/src/components/Forms/ModalForm.tsx, client/src/components/Forms/ModalSubmitForm.tsx, client/src/modules/CrossCheck/components/CriteriaForm.tsx, client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx, client/src/modules/CrossCheck/components/criteria/CrossCheckCriteriaModal.tsx, client/src/modules/Mentor/pages/Students/index.tsx, client/src/modules/Notifications/components/Consents.tsx, client/src/modules/Opportunities/components/EditCv/VisibleCoursesForm/index.tsx, client/src/modules/Opportunities/components/ViewCv/GratitudeSection/GratitudeList/index.tsx, client/src/modules/Score/pages/ScorePage/index.tsx, client/src/modules/Teams/components/MyTeamSection/MyTeamSection.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/course/admin/users.tsx, client/src/pages/course/student/dashboard.tsx, client/src/pages/profile/index.tsx, setup/cdk/package-lock.json, setup/cdk/package.json
=> refactor(eslint): add react, react-hooks plugins

nestjs/src/tasks/tasks.controller.ts
=> fix: security issue

.github/workflows/pull_request.yml, client/.eslintrc.js, client/package-lock.json, client/package.json, client/src/components/BadReview/BadReviewControllers.tsx, client/src/components/Forms/ModalForm.tsx, client/src/components/Forms/ModalSubmitForm.tsx, client/src/modules/CrossCheck/components/CriteriaForm.tsx, client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx, client/src/modules/CrossCheck/components/criteria/CrossCheckCriteriaModal.tsx, client/src/modules/Mentor/pages/Students/index.tsx, client/src/modules/Notifications/components/Consents.tsx, client/src/modules/Opportunities/components/EditCv/VisibleCoursesForm/index.tsx, client/src/modules/Opportunities/components/ViewCv/GratitudeSection/GratitudeList/index.tsx, client/src/modules/Score/pages/ScorePage/index.tsx, client/src/modules/Teams/components/MyTeamSection/MyTeamSection.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/course/admin/users.tsx, client/src/pages/course/student/dashboard.tsx, client/src/pages/profile/index.tsx, setup/cdk/package-lock.json, setup/cdk/package.json
Reverts rolling-scopes/rsschool-app#1982
=> Revert "Revert "refactor(eslint): add react, react-hooks plugins""

nestjs/src/auth/auth.controller.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/1945
Root cause is that auth cookie is not cleared after logout. 
=> fix: clear auth cookie

server/src/services/score/score.service.ts
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/1742)
=> feat: add cv link to excel

server/src/migrations/1675287680710-Course.ts, server/src/migrations/index.ts, server/src/models/course.ts
=> fix: update Course model

nestjs/src/courses/mentors/mentors.service.ts
* [] I followed naming convention rules
---
#1986 
- Show expelled students' solutions on mentor dashboard
=> fix(mentor-dashboard): show expelled students

client/src/components/Sider/data/menuItems.tsx, client/src/components/withSession.tsx, client/src/domain/user.ts, client/src/modules/Discipline/pages/DisciplinePage.tsx, client/src/modules/NotAccess/NotAccess.tsx, client/src/modules/NotAccess/index.ts, client/src/pages/admin/courses.tsx, client/src/pages/admin/disciplines.tsx, client/src/pages/admin/discord-server.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/pages/admin/notifications.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/admin/user-group.tsx, client/src/pages/admin/users.tsx, client/src/pages/course/mentor/expel-student.tsx, client/src/pages/course/mentor/interview-corejs.tsx, client/src/pages/course/mentor/interview-technical-screening.tsx, client/src/pages/course/student/cross-check-review.tsx, client/src/pages/course/student/cross-check-submit.tsx, nestjs/src/courses/course-access.service.ts, nestjs/src/courses/courses.controller.ts, nestjs/src/discord-servers/discord-servers.controller.ts, nestjs/src/events/events.controller.ts, server/src/routes/users/index.ts
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/2005)
=> refactor: review access to pages and functionality for powerUsers

client/src/pages/admin/tasks.tsx
=> fix: edit form opened with previous data after canceling

client/src/modules/Interviews/pages/InterviewFeedback/getServerSideProps.ts
=> fix: filter disabled interview

nestjs/src/courses/course-schedule/course-schedule.service.spec.ts, nestjs/src/courses/course-schedule/course-schedule.service.ts
=> fix: add shedule item type for cross-check submit

nestjs/src/courses/cross-checks/course-cross-checks.service.spec.ts, nestjs/src/courses/cross-checks/course-cross-checks.service.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/2039
Downloaded CSV with submitted solutions had amount of occurences for each record equal to number of checkeers. Removed duplicates
=> Deduplicate records in solutions urls csv

client/src/pages/course/admin/users.tsx, nestjs/src/courses/course-users/course-users.controller.spec.ts, nestjs/src/courses/course-users/course-users.controller.ts
=> fix: return empty error when course not has users

client/src/modules/Registry/components/Cards/AdditionalInfo/AdditionalInfo.test.tsx, client/src/modules/Registry/components/Cards/AdditionalInfo/AdditionalInfo.tsx, client/src/modules/Registry/components/FormSections/GeneralSection/GeneralSection.test.tsx, client/src/modules/Registry/components/FormSections/MentorshipSection/MentorshipSection.test.tsx, client/src/modules/Registry/components/FormSections/MentorshipSection/MentorshipSection.tsx, client/src/modules/Registry/hooks/useMentorData/useMentorData.tsx, client/src/modules/Registry/pages/Mentor/Mentor.tsx
---
Form should have preferred course pre-selected when opened with link containing course alias: 
```https://app.rs.school/registry/mentor?course=js-fe-2023Q1```
=> fix(mentor registration): add course preselect from direct link

client/src/components/Profile/ContactsCard.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2059
Added proper validation to Epam email field in Profile
=> feat: validate email correctly

nestjs/src/courses/task-verifications/task-verifications.service.ts
=> fix: task expiration check

client/src/pages/course/admin/tasks.tsx, nestjs/src/courses/course-tasks/course-tasks.service.ts
=> fix: add additional sorting params for get task

client/src/components/Forms/ModalForm.tsx, client/src/pages/course/admin/users.tsx
Reverts rolling-scopes/rsschool-app#2036
=> Revert "Fix: Previous course user name and roles appear in the modal"

client/src/modules/Mentor/pages/InterviewWaitingList/index.tsx
https://github.com/rolling-scopes/rsschool-app/issues/2028
For wait list actions we now show confirm dialog
=> feat: show confirmations for interview wait list actions

client/src/modules/CourseManagement/components/CourseEventModal/formState.ts
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/2077)
=> fix: update organizer id

client/src/pages/course/admin/tasks.tsx
=> fix: rerender modal when change data

client/src/modules/Opportunities/components/EditCv/index.test.tsx, client/src/modules/Opportunities/components/EditCv/index.tsx, client/src/pages/course/admin/tasks.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2073
Added notiication on succesfull save according to mockup + test case
On click "Save CV" button
Before  
After  
=> Add successful save notification

client/src/pages/admin/mentor-registry.tsx, nestjs/src/registry/registry.service.ts
---
[issue](https://github.com/rolling-scopes/rsschool-app/issues/2070)
=> fix: not show canceled mentor registry

client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx
=> fix: sort criteria form

client/src/modules/MentorRegistry/components/MentorRegistryTable.tsx, client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx, client/src/modules/MentorRegistry/constants.ts
---
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/2097)
_Describe the big picture of your changes here
_
=> feat: add cityname to mentorRegistry table on new tab

client/src/pages/admin/tasks.tsx
=> feat: add filter by type for tasks

client/src/modules/AutoTest/pages/AutoTests/AutoTests.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2119
Removed margin-right that led to scroll appearance
Before  
After  
=> Remove scroll on Auto-tests page

client/src/modules/Teams/Pages/Teams.tsx, client/src/modules/Teams/components/TeamModal/TeamModal.tsx
=> fix: add loader for submit team process

client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx
=> fix: fix incorrect discipline displaying in tags

client/src/modules/StudentDashboard/components/TasksStatsModal.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1363
=> fix: implement fix tasks statistics table position

client/src/modules/Teams/components/MyTeamSection/MyTeamSection.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2134
=> fix: password button style on mobile device

client/src/components/UserSearch.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/1889
Before
After
=> fix:  Add trim to whitespaces to search fields on score page

client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx
---
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/2110)
=> fix: change resend button visualization in mentorRegistryTable

client/src/modules/Registry/components/Cards/PersonalInfo/PersonalInfo.test.tsx, client/src/modules/Registry/components/Cards/PersonalInfo/PersonalInfo.tsx
=> fix: update required fields in registry form

client/src/api/api.ts, client/src/pages/course/admin/cross-check-table.tsx, nestjs/src/courses/cross-checks/course-cross-checks.service.ts, nestjs/src/courses/cross-checks/dto/check-tasks-pairs.dto.ts, nestjs/src/spec.json, server/src/models/taskSolutionResult.ts
=> feat: add historical score in cross-check table

client/src/api/api.ts, client/src/modules/MentorRegistry/components/MentorRegistryDeleteModal.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/services/mentorRegistry.ts, nestjs/src/registry/registry.controller.ts, nestjs/src/registry/registry.service.ts, nestjs/src/spec.json, server/src/repositories/mentorRegistry.repository.ts, server/src/routes/registry/index.ts
=> refactor: migrate cancel mentor registry route

client/src/modules/AutoTest/components/SelfEducation/SelfEducation.tsx
=> fix: fix broken multi-select questions

client/src/modules/AutoTest/components/Coding/Coding.tsx
---
[#2151](https://github.com/rolling-scopes/rsschool-app/issues/2151)
restore missing part
=> fix(codewars): slice hashed codewars nickname due length limit

client/src/api/api.ts, client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx, client/src/modules/CrossCheck/components/CrossCheckHistory.tsx, client/src/modules/CrossCheck/components/SolutionReview/Message/Message.test.tsx, client/src/modules/CrossCheck/components/SolutionReview/Message/Message.tsx, client/src/modules/CrossCheck/components/SolutionReview/MessageSendingPanel/MessageSendingPanel.tsx, client/src/modules/CrossCheck/components/SolutionReview/SolutionReview.tsx, client/src/modules/CrossCheck/components/SolutionReview/UserAvatar/UserAvatar.tsx, client/src/modules/CrossCheck/components/SolutionReview/Username/Username.test.tsx, client/src/modules/CrossCheck/components/SolutionReview/Username/Username.tsx, client/src/modules/CrossCheck/components/SolutionReview/helpers.ts, client/src/modules/CrossCheck/components/SolutionReviewSettingsPanel/SolutionReviewSettingsPanel.tsx, client/src/modules/CrossCheck/constants.ts, client/src/pages/course/admin/cross-check-table.tsx, client/src/pages/course/student/cross-check-review.tsx, client/src/services/course.ts, nestjs/src/courses/cross-checks/dto/check-tasks-pairs.dto.ts, nestjs/src/spec.json
=> feat: add cross-message in cross-check table

client/src/components/CommentModal.tsx, client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/pages/course/admin/cross-check-table.tsx, nestjs/src/courses/cross-checks/course-cross-checks.service.ts
=> fix: fix sorting in cross-check table

client/src/modules/Home/data/links.tsx, client/src/pages/admin/users.tsx, client/src/services/user.ts, server/src/routes/users/index.ts
=> feat: add search by discord for users

client/src/components/Sider/AdminSider.tsx
---
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/2161)
=> fix: fix sidebar view, save sidebar state using LS

client/src/modules/AutoTest/components/Question/Question.tsx, client/src/pages/course/mentor/interview-technical-screening.tsx
Reverts rolling-scopes/rsschool-app#2180
=> Revert "fix: update auto test answers layout"

client/src/modules/AutoTest/components/Exercise/Exercise.tsx, client/src/modules/AutoTest/hooks/useCourseTaskSubmit/useCourseTaskSubmit.ts
=> Fix double click on auto-test submit button

client/src/api/api.ts, client/src/components/Profile/DiscordCard.tsx, client/src/modules/CrossCheck/components/StudentContacts.tsx, client/src/services/user.ts, common/models/profile.ts, nestjs/src/core/dto/person.dto.ts, nestjs/src/courses/team-distribution/dto/team-distribution-student.dto.ts, nestjs/src/profile/dto/update-profile.dto.ts, nestjs/src/spec.json, server/src/routes/users/index.ts
Reverts rolling-scopes/rsschool-app#2198
=> Revert "feat: update discord type"

server/src/routes/course/student.ts
=> fix: update self assign student flow

client/src/components/Forms/CourseTaskSelect.tsx, client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap
---
#2160
Fix for select children (icon + text)
Expected result:
Actual result:
=> fix: select with icon has bad view

nestjs/src/profile/dto/personal-profile.dto.ts, nestjs/src/profile/profile.controller.ts, nestjs/src/profile/profile.service.ts
=> feat: add endpoint for getting personal profile

client/src/components/Profile/DiscordCard.tsx, client/src/components/StudentDiscord.tsx, client/src/components/__tests__/StudenDiscrod.test.tsx, client/src/modules/CrossCheck/components/CrossCheckAssignmentLink.tsx, client/src/modules/CrossCheck/components/SolutionReview/SolutionReview.tsx
=> fix: update discord card

client/src/api/api.ts, client/src/modules/Teams/components/StudentsTable/renderers.tsx, nestjs/src/courses/team-distribution/dto/team-distribution-student.dto.ts, nestjs/src/profile/dto/update-profile.dto.ts, nestjs/src/spec.json
=> fix: update discord column in teams page

client/src/modules/Home/data/links.tsx, client/src/modules/TeamDistribution/components/TeamDistributionCard/Actions.tsx, client/src/modules/TeamDistribution/components/TeamDistributionCard/TeamDistributionCard.tsx, client/src/modules/TeamDistribution/pages/TeamDistributions/TeamDistributions.tsx, nestjs/src/courses/team-distribution/registered-student-guard.ts, nestjs/src/courses/team-distribution/team-distribution.controller.ts, nestjs/src/courses/team-distribution/team.controller.ts
=> feat: add access in teams for dementors

client/src/modules/AutoTest/components/TaskCard/TaskCard.tsx
https://github.com/rolling-scopes/rsschool-app/issues/2209
Change the text of the "View details" button to "Open Task" to explicitly indicate the action.
=> refactor: change auto-test button text

client/src/components/Forms/CourseTaskSelect.tsx, client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap
=> feat: add filtering to CourseTaskSelect

client/package-lock.json, client/package.json, client/src/modules/Schedule/components/SettingsDrawer/ChangeTagColors.tsx, client/src/modules/Schedule/constants.ts
=> feat: migrate to color picker

client/src/api/api.ts, client/src/modules/Teams/components/TeamsSection/TeamsSection.tsx, nestjs/src/courses/team-distribution/team-distribution.controller.ts, nestjs/src/courses/team-distribution/team-distribution.service.ts, nestjs/src/courses/team-distribution/team.controller.ts, nestjs/src/courses/team-distribution/team.service.ts, nestjs/src/spec.json
=> feat: add command search functionality

client/src/components/BadReview/BadReviewControllers.tsx
---
add filtering to task select in BadReviewController
=> feat: add filtering to task select in BadReviewController

client/src/modules/CrossCheck/components/SolutionReview/SolutionReview.tsx
---
#2159
| Before | After |
| --- | --- |
| ![before](https://github.com/rolling-scopes/rsschool-app/assets/48645737/22830acc-d9bd-4e9c-b1ed-a643f113a0e5) | ![after](https://github.com/rolling-scopes/rsschool-app/assets/48645737/1b3162db-cac4-4dec-bb59-8f8d891a381c) |
=> fix: fix avatar position and message padding

client/src/modules/AutoTest/components/Question/Question.tsx, client/src/modules/AutoTest/components/SelfEducation/SelfEducation.tsx
---
#2247
| Before                                                                                                         | After                                                                                                         |
| -------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- …
=> feat: add gap between answers and change radio button position

client/src/components/Header.tsx
---
#2261
| Before                                                                                                         | After                                                                                                         |
| -------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- …
=> feat: improve Header layout for mobile

client/src/components/Forms/Heroes/index.tsx
---
[issue#2252](https://github.com/rolling-scopes/rsschool-app/issues/2252)
Before:
After:
=> fix: fix heroes form layout

client/src/domain/course.test.ts, client/src/domain/course.ts, client/src/domain/interview.test.ts, client/src/domain/interview.ts, client/src/modules/Interviews/pages/InterviewFeedback/getServerSideProps.ts, client/src/modules/Interviews/pages/InterviewFeedback/index.tsx, client/src/modules/Mentor/pages/Interviews/components/InterviewCard.tsx, client/src/modules/Mentor/pages/Interviews/components/InterviewDetails.tsx, client/src/modules/Mentor/pages/Interviews/components/InterviewsList.tsx, client/src/modules/Mentor/pages/Interviews/components/InterviewsSummary.tsx, client/src/modules/Mentor/pages/Interviews/components/StudentInterview.tsx, client/src/modules/Mentor/pages/Interviews/index.tsx, client/src/services/course.ts, common/models/stage-interview-feedback.ts, nestjs/src/courses/students/students.controller.ts, nestjs/src/courses/students/students.service.ts, server/src/migrations/1686657350908-InterviewScore.ts, server/src/migrations/index.ts, server/src/models/stageInterview.ts, server/src/models/stageInterviewFeedback.ts, server/src/repositories/interview.repository.ts, server/src/repositories/stageInterview.repository.ts
https://github.com/rolling-scopes/rsschool-app/issues/2112
- add new fields for stage interview(version & score).
- pass new params to interview to avoid breaking changes in further mrs
=> chore: add interview score & version. Add params for futher work

client/src/data/interviews/technical-screening.tsx, client/src/data/interviews/types.ts
This describes the new feedback template for technical screening interview/
=> feat: add interview feedback template

client/src/data/interviews/technical-screening.tsx, client/src/domain/interview.test.ts, client/src/domain/interview.ts, client/src/modules/Interviews/pages/InterviewFeedback/getServerSideProps.ts, client/src/modules/Interviews/pages/InterviewFeedback/index.tsx, client/src/modules/Interviews/pages/feedback/CustomQuestion.tsx, client/src/modules/Interviews/pages/feedback/Feedback.tsx, client/src/modules/Interviews/pages/feedback/FormItem.tsx, client/src/modules/Interviews/pages/feedback/NestedRadio.tsx, client/src/modules/Interviews/pages/feedback/QuestionCard.tsx, client/src/modules/Interviews/pages/feedback/QuestionList.tsx, client/src/modules/Interviews/pages/feedback/QuestionsPicker.tsx, client/src/modules/Interviews/pages/feedback/StepContext.tsx, client/src/modules/Interviews/pages/feedback/StepForm.tsx, client/src/modules/Interviews/pages/feedback/Steps.tsx, client/src/modules/Interviews/pages/feedback/StepsContent.tsx, client/src/modules/Interviews/pages/feedback/StudentInfo.tsx, client/src/modules/Interviews/pages/feedback/SubHeader.tsx, client/src/modules/Interviews/pages/feedback/feedbackTemplateHandler.test.ts, client/src/modules/Interviews/pages/feedback/feedbackTemplateHandler.ts, client/src/modules/Interviews/pages/feedback/index.ts, client/src/pages/course/interview/[type]/feedback.tsx
Adds new Feedback page based on the template for interview feedback
=> feat(interview): add new feedback page

client/src/pages/profile/index.tsx
=> fix: update profile info request

client/src/components/Profile/PrescreeningFeedback.tsx, client/src/services/features.tsx
=> feat: enable new feedback template

client/src/components/Sider/AdminSider.tsx, client/src/modules/Score/components/ScoreTable/index.tsx, client/src/pages/admin/mentor-registry.tsx
=> fix: update score height

server/src/routes/course/crossCheck/createMessage.ts
=> fix: find checker user id

client/src/modules/Opportunities/components/EditCv/index.test.tsx, client/src/modules/Opportunities/components/NoConsentView/index.test.tsx, client/src/modules/Opportunities/components/ViewCv/ContactsSection/ContactsList/index.test.tsx
=> test: fix disabled tests

client/src/modules/Schedule/components/MobileItemCard/MobileItemCard.tsx, client/src/modules/Schedule/components/TableView/TableView.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2312
=> feat(schedule): update schedule mobile view with user timezone offset

client/src/modules/TeamDistribution/components/SubmitScoreModal/SubmitScoreModal.tsx, client/src/modules/TeamDistribution/components/SubmitScoreModal/index.tsx, client/src/modules/TeamDistribution/components/TeamDistributionCard/Actions.tsx, client/src/modules/TeamDistribution/components/TeamDistributionCard/TeamDistributionCard.test.tsx, client/src/modules/TeamDistribution/components/TeamDistributionCard/TeamDistributionCard.tsx, client/src/modules/TeamDistribution/hooks/useSubmitTeamScore.test.tsx, client/src/modules/TeamDistribution/hooks/useSubmitTeamScore.tsx, client/src/modules/TeamDistribution/pages/TeamDistributions/TeamDistributions.tsx
---
I was too lazy to create an issue, please understand and forgive me.
=> feat: add submit team score modal

client/src/components/Forms/Heroes/index.tsx, client/src/components/Heroes/HeroesRadarTab.tsx, client/src/pages/heroes.tsx
=> fix(heroes): show only user's courses

client/src/modules/CrossCheck/components/SubmittedStatus.tsx
---
| Before | After |
|-|-|
| ![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/47406f74-1170-4150-a31c-791a8e1465bf) | ![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/2d17b236-cbc1-4bd9-a59d-3e7b37cc7d6d) |
=> feat(cross-check): add tip

client/src/modules/AutoTest/components/VerificationInformation/VerificationInformation.test.tsx, client/src/modules/Course/contexts/SessionContext.test.tsx, client/src/modules/TeamDistribution/hooks/useSubmitTeamScore.test.tsx, nestjs/src/courses/team-distribution/team-distribution-student.service.ts
=> fix: disctribute only active students

nestjs/src/tasks/dto/task.dto.ts
=> fix: filter disabled course tasks

client/src/data/interviews/angular.ts, client/src/data/interviews/index.ts
=> feat: add Angular inteview

client/src/pages/course/student/auto-test/task.tsx, nestjs/src/courses/task-verifications/task-verifications.service.ts
=> fix: auto-tests access

client/src/pages/course/student/auto-test/index.tsx
=> fix: change auto-tests visibility rules

client/src/modules/AutoTest/utils/map.ts
=> fix: move passed test to Done tab

client/src/components/Profile/LanguagesCard.tsx
=> fix: add wrap on profile languages

nestjs/src/courses/course-schedule/course-schedule.service.ts
Reverts rolling-scopes/rsschool-app#2364
=> Revert "feat: update schedule sort rules"

client/src/modules/StudentDashboard/components/NextEventCard/renderers.tsx, client/src/pages/course/student/dashboard.tsx
---
[PR#2364](https://github.com/rolling-scopes/rsschool-app/pull/2364)
Schedule:
Dashboard:
Before: 
After:
Also fixed: 
=> feat: update available tasks sorting

client/src/api/api.ts, nestjs/src/courses/team-distribution/team-distribution.controller.ts, nestjs/src/spec.json
=> fix: fix parameter order in teamDistributionDeleteRegistry endpoint

client/src/components/Profile/MainCard.tsx, client/src/components/Profile/ObfuscateConfirmationModal.tsx
=> feat: add obfuscate confirmation modal

client/src/modules/Score/components/ScoreTable/index.tsx, client/src/modules/Score/hooks/types.ts, client/src/utils/optionalQueryString.ts, client/src/utils/queryParams-utils.ts
---
https://app.rs.school/course/score
=> feat: implement feature trim function to the search inputs on the score

client/src/modules/Score/components/ScoreTable/index.tsx, client/src/modules/Score/data/getColumns.tsx, client/src/modules/Score/hooks/useScorePaging.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2311
=> fix: add default value for githubId and name fields and fix reset bug

nestjs/src/courses/course-tasks/course-tasks.service.ts
https://github.com/rolling-scopes/rsschool-app/issues/2319
=> fix: add buffer for quering pending tasks

package-lock.json, server/package.json
=> refactor: fix migrations

client/src/data/interviews/technical-screening.tsx, nestjs/src/courses/course-tasks/course-tasks.service.ts
---
[issue](https://github.com/rolling-scopes-school/tasks/issues/1419)
=> feat: update technical screening template

nestjs/src/courses/team-distribution/team-distribution.controller.ts
=> fix: update permissions submit team score

nestjs/src/profile/dto/endorsement.dto.ts, nestjs/src/profile/endorsement.service.ts, nestjs/src/profile/profile.controller.ts
=> feat: expose endpoint with endorsement data

client/src/components/PageLayout.tsx, client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsCard.tsx, client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsChart.tsx, client/src/modules/AdminDashboard/pages/AdminDashboard.tsx, client/src/pages/course/admin/dashboard.tsx
=> fix: update page layout

client/src/modules/Course/contexts/SessionContext.tsx, client/src/pages/admin/courses.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/pages/admin/tasks.tsx, client/src/pages/admin/users.tsx
=> fix: add any course allowed role to Session context

docs/platform/about.md
=> docs: fix leave course button description

client/src/components/Forms/MarkdownInput.tsx
---
https://github.com/rolling-scopes/rsschool-app/issues/2254
=> feat: show field error message in preview mode

client/src/api/api.ts, client/src/modules/AdminDashboard/components/CountriesChart/CountriesChart.tsx, client/src/modules/AdminDashboard/components/MentorsCountriesCard/MentorsCountriesCard.tsx, client/src/modules/AdminDashboard/components/StudentsCountriesCard/StudentsCountriesCard.tsx, client/src/modules/AdminDashboard/hooks/useCourseStats/useCourseStats.tsx, client/src/modules/AdminDashboard/pages/AdminDashboard.tsx, nestjs/src/courses/stats/course-stats.controller.ts, nestjs/src/courses/stats/course-stats.service.ts, nestjs/src/courses/stats/dto/countries-stats.dto.ts, nestjs/src/courses/stats/dto/course-mentors-stats.dto.ts, nestjs/src/courses/stats/dto/index.ts, nestjs/src/spec.json
=> feat: add Mentor Statistics

client/src/modules/Home/pages/HomePage/index.tsx
=> fix: remove banner for admins

client/src/modules/AdminDashboard/components/CountriesChart/CountriesChart.tsx, client/src/modules/AdminDashboard/components/EpamMentorsStatsCard/EpamMentorsStatsCard.tsx, client/src/modules/AdminDashboard/components/EpamMentorsStatsCard/index.tsx, client/src/modules/AdminDashboard/components/LiquidChart/LiquidChart.tsx, client/src/modules/AdminDashboard/components/MentorsCountriesCard/MentorsCountriesCard.tsx, client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsCard.tsx, client/src/modules/AdminDashboard/components/data.ts, client/src/modules/AdminDashboard/pages/AdminDashboard.tsx
=> feat: add epam mentors stats

client/src/pages/course/admin/stage-interviews.tsx
=> fix: show cancel interview button for supervisor

client/src/pages/course/interview/[type]/feedback.tsx, nestjs/src/courses/interviews/interviews.controller.ts
=> fix: update page access

nestjs/src/courses/students/students.service.ts
=> fix: update access to students

server/src/services/course.service.ts
=> fix: fix interview issue

client/src/components/Forms/ModalForm.tsx, client/src/components/StudentMentorModal.tsx, client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx, client/src/modules/CourseManagement/components/CoursesListModal/index.tsx, client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx, client/src/pages/admin/courses.tsx, client/src/pages/admin/discord-server.tsx, client/src/pages/admin/events.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/pages/admin/user-group.tsx, client/src/pages/course/admin/users.tsx, package-lock.json, package.json
=> fix: do not render modal at all if no data

client/src/data/interviews/corejs1.ts
---
[issue](https://github.com/rolling-scopes-school/tasks/issues/1498)
=> feat: update core js interview template

client/src/api/api.ts, client/src/modules/CrossCheckPairs/data/getCrossCheckPairsColumns.tsx, nestjs/src/courses/cross-checks/course-cross-checks.service.ts, nestjs/src/courses/cross-checks/dto/check-tasks-pairs.dto.ts, nestjs/src/spec.json
---
I was too lazy to create an issue, please understand and forgive.
=> feat: add private repo link to cross-check page

client/src/api/api.ts, client/src/modules/AdminDashboard/components/StudentsCountriesCard/StudentsCountriesCard.tsx, client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsCard.tsx, client/src/modules/AdminDashboard/components/StudentsWithCertificateCard/StudentsWithCertificateCard.tsx, client/src/modules/AdminDashboard/components/StudentsWithCertificateCard/index.tsx, client/src/modules/AdminDashboard/components/StudentsWithMentorsCard/StudentsWithMentorsCard.tsx, client/src/modules/AdminDashboard/components/data.ts, client/src/modules/AdminDashboard/pages/AdminDashboard.tsx, client/src/modules/Interviews/pages/InterviewFeedback/getServerSideProps.ts, client/src/pages/course/student/dashboard.tsx, nestjs/src/courses/stats/course-stats.service.ts, nestjs/src/courses/stats/dto/course-stats.dto.ts, nestjs/src/spec.json
=> feat: add widget students with certificate

nestjs/src/courses/course-tasks/course-tasks.service.ts, nestjs/src/courses/course-tasks/dto/course-task-detailed.dto.ts
=> fix: update task result count calculation

server/src/services/course.service.ts
=> fix: export all emails in csv

client/src/api/api.ts, client/src/modules/AdminDashboard/components/DonutChart/DonutChart.tsx, client/src/modules/AdminDashboard/components/TaskPerformanceCard/TaskPerformanceCard.tsx, client/src/modules/AdminDashboard/components/TaskPerformanceCard/index.tsx, client/src/modules/AdminDashboard/components/data.ts, client/src/modules/AdminDashboard/hooks/useCourseStats/useCourseStats.tsx, client/src/modules/AdminDashboard/pages/AdminDashboard.tsx, nestjs/src/courses/stats/course-stats.controller.ts, nestjs/src/courses/stats/course-stats.service.ts, nestjs/src/courses/stats/dto/index.ts, nestjs/src/courses/stats/dto/task-performance-stats.dto.ts, nestjs/src/spec.json
=> feat: add task performance widget

client/src/modules/CourseStatistics/components/MentorsCountriesCard/MentorsCountriesCard.tsx, client/src/modules/CourseStatistics/components/TaskPerformanceCard/TaskPerformanceCard.tsx, client/src/modules/CourseStatistics/data.ts
=> fix update tooltip for task performance widget

nestjs/src/certificates/certificates.controller.ts, nestjs/src/certificates/certificates.module.ts, nestjs/src/certificates/certificates.service.ts, nestjs/src/certificates/dto/certificate-metadata.dto.ts
=> feat: return certificate metadata if append .json to certificate id

nestjs/src/certificates/dto/certificate-metadata.dto.ts
=> feat: add course type to certificate metadata

client/src/api/api.ts, client/src/components/Sider/data/menuItems.tsx, client/src/components/Table/renderers.tsx, client/src/modules/MetorTasksReview/components/ReviewsTable/index.tsx, client/src/modules/MetorTasksReview/components/ReviewsTable/renderers.tsx, client/src/modules/MetorTasksReview/pages/MentorTasksReview.tsx, client/src/modules/Schedule/components/TableView/TableView.tsx, client/src/modules/StudentDashboard/components/NextEventCard/renderers.tsx, client/src/pages/course/admin/mentor-tasks-review.tsx, nestjs/src/courses/courses.module.ts, nestjs/src/courses/mentor-reviews/dto/index.ts, nestjs/src/courses/mentor-reviews/dto/mentor-reviews-query.dto.ts, nestjs/src/courses/mentor-reviews/dto/mentor-reviews.dto.ts, nestjs/src/courses/mentor-reviews/index.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.controller.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.service.ts, nestjs/src/spec.json, server/src/models/taskChecker.ts
=> feat: implement mentor reviews page

setup/backup-local.sql
=> refactor: update snapshot

client/src/modules/MentorRegistry/components/MentorRegistryTable.tsx, client/src/modules/MentorRegistry/constants.ts, nestjs/src/registry/registry.controller.ts, nestjs/src/registry/registry.service.ts
=> fix: update mentor registry search

client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx, client/src/services/validators.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/2451
- small refactoring (avoid using of one-time called funcs without params)
- just addition of extra validation to link submission input  
Before    
After  
=> feat: prohibit submission of links to private RS repos

client/src/api/api.ts, client/src/modules/CourseStatistics/components/StudentsCertificatesCountriesCard/StudentsCertificatesCountriesCard.tsx, client/src/modules/CourseStatistics/components/StudentsCertificatesCountriesCard/index.tsx, client/src/modules/CourseStatistics/hooks/useCourseStats/useCourseStats.tsx, client/src/modules/CourseStatistics/pages/CourseStatistics.tsx, nestjs/src/courses/stats/course-stats.controller.ts, nestjs/src/courses/stats/course-stats.service.ts, nestjs/src/spec.json
=> feat: add certificates countries widget

client/src/api/api.ts, client/src/modules/MetorTasksReview/components/ReviewsTable/index.tsx, client/src/modules/MetorTasksReview/components/ReviewsTable/renderers.tsx, client/src/modules/MetorTasksReview/pages/MentorTasksReview.tsx, client/src/modules/MetorTasksReview/pages/getServerSideProps.ts, client/src/pages/course/admin/mentor-tasks-review.tsx, nestjs/src/courses/course-tasks/course-tasks.controller.ts, nestjs/src/courses/course-tasks/course-tasks.service.ts, nestjs/src/courses/mentor-reviews/dto/mentor-reviews-query.dto.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.controller.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.service.ts, nestjs/src/spec.json
=> feat: add filter for mentors review table

client/src/modules/Score/components/SettingsModal/index.tsx
=> refactor: update SettingsModal on score page

nestjs/src/courses/course-mentors/course-mentors.service.ts
=> fix: add mentor email to export file

client/src/modules/StudentDashboard/components/MentorInfo/MentorInfo.tsx, client/src/modules/Tasks/components/TasksTable/TasksTable.tsx
=> Feat: add filter search

client/src/api/api.ts, client/src/modules/Feedback/components/FeedbackForm.tsx, client/src/modules/Feedback/data/softSkills.ts, client/src/modules/Mentor/hooks/useMentorStudents.tsx, client/src/modules/Mentor/pages/StudentFeedback/index.tsx, client/src/modules/Mentor/pages/Students/index.tsx, nestjs/src/courses/mentors/dto/mentor-student.dto.ts, nestjs/src/courses/mentors/mentors.controller.ts, nestjs/src/courses/mentors/mentors.service.ts, nestjs/src/spec.json
=> feat: Add Functionality for Mentors to Edit Feedback for Students

client/package.json, client/src/api/api.ts, client/src/modules/MentorRegistry/components/InviteMentorsModal.tsx, client/src/pages/admin/mentor-registry.tsx, client/src/services/mentorRegistry.ts, nestjs/src/notifications/email-template.ts, nestjs/src/notifications/notifications.service.ts, nestjs/src/registry/dto/invite-mentors.dto.ts, nestjs/src/registry/registry.controller.ts, nestjs/src/registry/registry.module.ts, nestjs/src/registry/registry.service.ts, nestjs/src/spec.json, package-lock.json, server/src/models/notification.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/2069
Adds the ability to send e-mail to students to join as mentors
=> Invite mentors

client/src/data/interviews/react.ts
=> feat: update react interview template

client/src/api/api.ts, client/src/modules/MetorTasksReview/components/ReviewsTable/renderers.tsx, client/src/modules/MetorTasksReview/pages/MentorTasksReview.tsx, nestjs/src/courses/mentor-reviews/dto/mentor-reviews-query.dto.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.controller.ts, nestjs/src/courses/mentor-reviews/mentor-reviews.service.ts, nestjs/src/spec.json
=> feat: add seacrh by student for mentors review

client/src/modules/CrossCheck/AddCriteriaForCrossCheck.tsx, client/src/modules/CrossCheck/CriteriaActions.tsx, client/src/modules/CrossCheck/CriteriaTypeSelect.tsx, client/src/modules/CrossCheck/EditableCellForCrossCheck.tsx, client/src/modules/CrossCheck/EditableCriteriaInput.tsx, client/src/modules/CrossCheck/EditableTableForCrossCheck.tsx, client/src/modules/CrossCheck/ExportJSONButton.tsx, client/src/modules/CrossCheck/UploadCriteriaJSON.tsx, client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx, client/src/modules/CrossCheck/components/criteria/CrossCheckCriteria.tsx, client/src/modules/CrossCheck/constants.ts, client/src/modules/Tasks/pages/TasksPage/TasksPage.tsx, client/src/pages/course/student/cross-check-review.tsx
---
#2405 
Admin / Tasks / Criteria for Cross-Check task:  
- Edit type of task
- Cancel changes
https://github.com/user-attachments/assets/ee49d2f3-9f5b-43c6-9a2c-dba080717e73
=> feat: Edit criterion type functionality

client/src/pages/gratitude.tsx, nestjs/src/gratitudes/dto/create-gratitude.dto.ts
---
https://github.com/rolling-scopes/rsschool-app/issues/2543
Before  
After  
+ BE validation  
=> fix: don't allow "@" in gratitude comment

client/src/modules/Schedule/components/StatusTabs/StatusTabs.test.tsx, client/src/modules/Schedule/constants.ts, nestjs/src/config/config.service.ts, nestjs/src/courses/course-schedule/course-schedule.service.spec.ts
=> Fix: schedule tests

nestjs/src/courses/course-schedule/course-schedule.service.ts
=> feat: integrate team distribution handling in course schedule transfer

client/src/pages/course/admin/tasks.tsx
=> feat: add column search functionality for task name in admin tasks table

client/src/modules/Notifications/components/Consents.tsx
=> fix: update telegram banner message

client/src/api/api.ts, client/src/components/UserSearch.tsx, client/src/modules/CrossCheck/components/CriteriaForm.tsx, client/src/modules/StudentDashboard/components/RepositoryCard.tsx, client/src/pages/admin/auto-test-task.tsx, client/src/pages/admin/users.tsx, nestjs/src/courses/interviews/interviews.service.ts, nestjs/src/gratitudes/gratitudes.service.ts, nestjs/src/profile/profile.service.ts, nestjs/src/spec.json, nestjs/src/users/dto/index.ts, nestjs/src/users/dto/user-search.dto.ts, nestjs/src/users/users.controller.ts, nestjs/src/users/users.module.ts, nestjs/src/users/users.service.ts, package-lock.json, package.json, server/src/models/session.ts, setup/docker-compose.yml
=> feat: extending user search with information about being mentor and student

client/src/domain/interview.tsx, client/src/modules/Interviews/pages/InterviewFeedback/getServerSideProps.ts, client/src/modules/Mentor/pages/InterviewWaitingList/getServerSideProps.ts, client/src/modules/Mentor/pages/InterviewWaitingList/index.tsx, client/src/modules/Mentor/pages/Interviews/components/RegistrationNoticeAlert.tsx, client/src/modules/Mentor/pages/Interviews/index.tsx, client/src/pages/course/admin/events.tsx, client/src/pages/course/admin/tasks.tsx, client/src/pages/course/interview/[type]/feedback.tsx, client/src/pages/course/student/interviews.tsx
=> fix: update interview query

nestjs/src/users/users.service.ts
=> feat: enhance user search functionality with multi-term support

client/src/api/api.ts, client/src/modules/CourseManagement/components/CourseModal/index.tsx, client/src/modules/Opportunities/components/PublicLink/index.test.tsx, nestjs/src/courses/dto/course.dto.ts, nestjs/src/courses/dto/create-course.dto.ts, nestjs/src/courses/dto/export-course.dto.ts, nestjs/src/courses/dto/update-course.dto.ts, nestjs/src/spec.json, server/src/migrations/1736458672717-Course.ts, server/src/migrations/index.ts, server/src/models/course.ts, setup/backup-local.sql
=> feat: add "wearecommunityUrl"

client/src/data/interviews/index.ts, client/src/data/interviews/shortTrackScreening.ts, client/src/data/interviews/stScreening.ts
---
Added Technical screening interview template for EPAM ST 2025 Q1
=> feat: add EPAM ShortTrack 2025 Q1 technical screening template

client/src/data/interviews/shortTrackScreening.ts
=> fix: fixed link and some ids in the template

client/src/pages/course/student/interviews.tsx
=> fix: stage interviews status

nestjs/src/courses/dto/export-course.dto.ts
---
-
Jusr a renaming start date property according to common sense
=> fix: typo in exported personal mentoring start date

client/src/modules/Registry/components/Cards/CourseDetails/CourseDetails.tsx, client/src/modules/Registry/components/CourseLabel/CourseLabel.tsx, client/src/modules/Registry/constants/index.ts
---
- Closes #2591
**Dates added to clarify when a mentor is involved in the course activities** (http://localhost:3000/registry/mentor)
**Before the fix:**
**Student form is not affected**
http://localhost:3000/registry/student
=> Refactor: add mentoring dates to registration form

nestjs/src/courses/task-verifications/self-education.service.ts, nestjs/src/courses/task-verifications/task-verifications.service.ts, nestjs/src/registry/registry.service.ts
=> fix: ensure canceled mentor registries are excluded from queries

client/src/data/interviews/index.ts, client/src/data/interviews/shortTrackJavaScript.ts, client/src/data/interviews/shortTrackTypeScript.ts
=> feat: add EPAM ShortTrack TS mentors interview #2

docker-compose.yml
=> fix: add Anya to admins

nestjs/src/courses/interviews/interviews.service.ts
=> fix: do not return disabled interviews by default

client/src/data/interviews/index.ts, client/src/data/interviews/shortTrackPerformance.ts
=> Add EPAM ShortTrack TS mentors interview #3

client/src/modules/Score/data/getColumns.tsx
=> fix: add antd button, change ColumnType import to tree-shaking version

client/src/components/Table/columns.tsx
=> fix: focus automatically move to the search input field

client/src/modules/Teams/components/TeamsHeader/ActionCard.tsx
=> fix: add confirmation to rs teams action card buttons

client/src/domain/interview.tsx, client/src/modules/Interview/Student/components/InterviewCard.tsx, client/src/modules/Interview/Student/data/getInterviewCardDetails.tsx, client/src/modules/Interviews/pages/feedback/feedbackTemplateHandler.ts
=> fix: add correct sloth images for interview results

client/src/api/api.ts, client/src/components/Student/DashboardDetails.tsx, client/src/pages/course/admin/students.tsx, client/src/services/course.ts, nestjs/src/certificates/certificates.controller.ts, nestjs/src/certificates/certificates.module.ts, nestjs/src/certificates/certificates.service.ts, nestjs/src/spec.json
=> feat: add ability to delete the issued RS School certificate

nestjs/src/registry/registry.service.ts
=> fix: add mentors with empty prefered to new applications

docker-compose.yml
=> chore: extend admins list

setup/cdk/Stack.ts, setup/cdk/package-lock.json, setup/cdk/package.json
=> fix: update aws-cdk & aws-cdk-lib versions, change class CloudFrontWebDistribution to Distribution

client/src/modules/Mentor/pages/Interviews/components/InterviewsList.tsx, client/src/modules/Mentor/pages/Interviews/components/StudentInterview.tsx
=> fix: add interviewTaskType check for popconfirm

.github/pull_request_template.md, CONTRIBUTING.md
I want to simplify our PR template as it has tons of boilerplate. Need to reduce noise.
=> fix: update PR template

nestjs/jest.config.mjs, nestjs/package.json, nestjs/src/courses/task-verifications/dto/index.ts, nestjs/src/courses/task-verifications/dto/self-education.dto.ts, nestjs/src/courses/task-verifications/dto/task-verifications-attempts.dto.ts, nestjs/src/courses/task-verifications/self-education.service.test.ts, nestjs/src/courses/task-verifications/self-education.service.ts, nestjs/src/courses/task-verifications/task-verifications.controller.ts, nestjs/src/courses/task-verifications/task-verifications.service.ts, server/src/models/taskVerification.ts
**Issue**:
#2690 
Fixing possibility to cheat self-education validation and add test-suite 
=> fix: self education validation

client/src/modules/StudentDashboard/components/RepositoryCard.tsx, client/src/pages/course/student/dashboard.tsx
**Issue**:
N/A
Fixes showing the repository URL after refactoring
=> fix: repository url on student dashboard

client/src/modules/AutoTest/components/Coding/Coding.test.tsx, client/src/modules/AutoTest/components/Coding/Coding.tsx
**Issue**:
N/A
Just an update of Node.js version in auto-test JS task submission view  
=> fix: update node.js version in warning

docker-compose.yml
**Issue**:
_Link to the relevant GitHub Issue (e.g., `#123` for issue number 123)._
_Please provide a description of the changes in this Pull Request. Include screenshots or GIFs if applicable. The description should clearly explain the purpose of this PR._
=> fix: update RSSHCOOL_USERS_ADMINS list

client/src/components/Header.tsx
**Issue**:
_Link to the relevant GitHub Issue (e.g., `#123` for issue number 123)._
_Please provide a description of the changes in this Pull Request. Include screenshots or GIFs if applicable. The description should clearly explain the purpose of this PR._
=> fix: update help link in Header component

nestjs/src/courses/interviews/interviews.service.ts, server/src/repositories/interview.repository.ts, server/src/services/interview.service.ts
Make zero a valid result and status for interview.
=> fix: return zero result for interview

client/src/modules/CourseManagement/components/CourseModal/index.tsx, client/src/services/validators.ts
=> fix: add default RS App URL with validation

client/src/api/api.ts, client/src/modules/Teams/Pages/Teams.tsx, client/src/modules/Teams/components/StudentsTable/StudentsTable.tsx, client/src/modules/Teams/components/StudentsTable/renderers.tsx, client/src/modules/Teams/components/StudentsWithoutTeamSection/StudentsWithoutTeamSection.tsx, client/src/modules/Teams/constants.ts, nestjs/src/courses/team-distribution/team-distribution.controller.ts, nestjs/src/courses/team-distribution/team.service.ts, nestjs/src/spec.json
**Issue**:
https://github.com/rolling-scopes/rsschool-app/issues/2687
_Please provide a description of the changes in this Pull Request. Include screenshots or GIFs if applicable. The description should clearly explain the purpose of this PR._
=> feat: implement student deletion from team distribution

client/src/pages/admin/mentor-registry.tsx
**Issue**:
#2734
No more rerender tab component (All Mentor).
https://github.com/user-attachments/assets/ad3d74e0-289e-4f34-85cd-d4c3d2f92237
=> fix: change style of tabs component and fix logic of handleTabChange

client/src/components/NonTouchTooltip.tsx, client/src/components/Profile/ContactsCard.tsx, client/src/components/RegistrationPageLayout.tsx, client/src/components/ThemeSwitch.tsx, client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx, client/src/modules/CrossCheck/components/criteria/PenaltyCriteria.tsx, client/src/modules/CrossCheck/components/criteria/SubtaskCriteria.tsx, client/src/modules/CrossCheck/components/criteria/TitleCriteria.tsx, client/src/modules/CrossCheck/utils/getCriteriaStatusColor.ts, client/src/modules/Mentor/components/TaskSolutionsTable/TaskSolutionsTable.tsx, client/src/modules/Opportunities/pages/EditPage/index.tsx, client/src/modules/Schedule/components/FilteredTags/FilteredTags.tsx, client/src/modules/Schedule/components/MobileItemCard/MobileItemCard.tsx, client/src/providers/ThemeProvider.tsx, client/src/styles/main.css
**Issue**:
[Dark theme: color mismatch](https://github.com/rolling-scopes/rsschool-app/issues/2763)
- Updated colors for the mentor's dashboard
- Updated colors for schedule table
- Updated theme toggle's tooltip behavior (tooltip now placed at the left of the icon and hidden on touchable devices)
- Updated colors for cross-check form
- By default light theme is selected
- Custom scroll bars for window, ant-design table and ant-design modal
=> FIX: dark theme colors mismatch

nestjs/package.json, nestjs/src/profile/endorsement.service.ts, package-lock.json
**Issue**:
We use very old OpenAI model (gpt-3.5)
Updating from gpt-3.5 to gpt-5
=> feat: update openai package and switch to gpt-5

client/src/modules/Course/contexts/ActiveCourseContext.tsx, client/src/modules/Registry/hooks/useMentorData/useMentorData.tsx, client/src/modules/Registry/hooks/useStudentData/useStudentData.tsx, client/src/modules/Registry/pages/Mentor/Mentor.tsx, client/src/modules/Registry/pages/Student/Student.tsx, client/src/pages/_app.tsx, client/src/pages/registry/mentor.tsx, client/src/pages/registry/student.tsx
**Issue**:
_Link to the relevant GitHub Issue (e.g., `#123` for issue number 123)._
_Please provide a description of the changes in this Pull Request. Include screenshots or GIFs if applicable. The description should clearly explain the purpose of this PR._
=> fix: registration

nestjs/src/auth/auth.service.ts, nestjs/src/core/paginate/index.test.ts, nestjs/src/core/paginate/index.ts
**Issue**:
Fixing "OFFSET must not be negative" error
Making skip max value as 0
=> fix(paginate): skip could not be negative

client/src/data/interviews/angular.ts
**Issue**:
- [Multiple checkboxes are checked at the same time](https://github.com/rolling-scopes/rsschool-app/issues/2832)
Angular interview template has repeated question IDs.
**NB!** Previously submitted data potentially incorrect (in DB: table `task_interview_result` , column `formAnswers`)
=> Incorrect question IDs
