client/src/components/Profile/StudentStatsModal.tsx
client/src/components/Profile/__test__/__snapshots__/StudentStatsModal.test.tsx.snap

Displayed maximum score value is now rounded to 1 decimal place. [Fixed issue](https://github.com/rolling-scopes/rsschool-app/issues/429).

fix: rounding total score issue

---

client/src/pages/course/student/auto-test.tsx
client/src/services/course.ts
server/src/routes/course/taskVerification.ts
server/src/routes/index.ts

New flag `strictAttemptsMode` can be added to json file for selfeducation task config.
It can be set up as `false`. It lets students to submit the task even if limit of attempts is over. They'll get half a score in that case.
It's `true` by default.
**JSON.Attributes example:**
```
{
"public": {
"tresholdPercentage": 70,
"numberOfQuestions": 10,
"maxAttemptsNumber": 2,
"strictAttemptsMode": false,
"questions": [
{
"question": "Do you like html?",
"answers": ["Yes", "No", "Maybe"],
"multiple": false
},
{
"question": "What is css?",
"answers": ["Cascade style sheets", "cosmic super solutions", "cool super stuff"],
"multiple": true
},
{
"question": "What is not a css selector?",
"answers": ["<div>", "div", "a.a", "p<div>"],
"multiple": true
}
]
},
"answers": [
[0],
[0, 2],
[0, 3]
]
}
```

feat: update selfeducation task with strict mode

---

client/src/styles/main.css

Add styles for ant design radio component, which restore normal white-space.
PR fixes #629 #639

fix: add words breaking in radio

---

client/src/components/Table/sorters.ts

This fixes #752
Now empty values will stay at the bottom all the time.

Fix the bug with sorting values in the table

---

client/src/pages/course/student/auto-test.tsx
client/src/services/course.ts

New flags `questionImage` and `answersType` can be added to json file for RSAPP Task config.
They are optional.
`"questionImage": "https://urlwhereyoustoreyourimage.com"` - let you show some image under the question text
`"answersType": "image"` - let you put url to answers and show image instead of answer's text.
**JSON.Attributes example:**
```
{
"public": {
"tresholdPercentage": 70,
"numberOfQuestions": 10,
"maxAttemptsNumber": 2,
"strictAttemptsMode": false,
"questions": [
{
"question": "Look at the picture and select the right answer",
"questionImage": "https://i.imgur.com/I8z0Pzw.jpeg",
"answersType": "image",
"answers": [
"https://i.imgur.com/1E6cZuv.jpeg",
"https://i.imgur.com/Br5yYVc.jpeg",
"https://i.imgur.com/Nrqih1V.jpeg"
],
"multiple": false
},
{
"question": "What is css?", …
```

feat: add pictures for RSSAPP Tests

---

client/src/pages/course/student/auto-test.tsx
client/src/services/course.ts
server/src/routes/course/taskVerification.ts

---
Fixes #901 
**How enable it**
You need to add `oneAttemptPerNumberOfHours` option to task JSON with the number of hours. 0 is used by default and means that this option is disabled.
Example:
```javascript
{
"public": {
"maxAttemptsNumber": 22,
"numberOfQuestions": 2,
"strictAttemptsMode": true,
"tresholdPercentage": 85,
"oneAttemptPerNumberOfHours": 8,
"questions": [
// ...
]
},
"answers": [
// ...
]
}
```
How it's shown on the client:

feat: limit tries for auto-tests

---

client/src/components/GithubAvatar.tsx
client/src/components/GithubUserLink.tsx
client/src/components/Profile/MentorStatsModal.tsx
client/src/components/Profile/PublicFeedbackCard.tsx
client/src/components/Profile/PublicFeedbackModal.tsx
client/src/components/Profile/__test__/__snapshots__/MentorStatsModal.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/PublicFeedbackCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/PublicFeedbackModal.test.tsx.snap
client/src/config.ts
client/src/configs/cdn.ts

---
N/A
Let's switch to caching Github avatars on own side in order to prevent rate limiting on Github.
Now you can get user avatar by replacing "github.com" with "cdn.rs.school".
E.g. https://cdn.rs.school/apalchys.png

feat: switch to own CDN for Github avatars

---

client/src/components/AdminSider.tsx
client/src/components/Footer/Menu.tsx
client/src/components/Schedule/EventDetails.tsx
client/src/components/Schedule/ListView.tsx
client/src/components/Schedule/TaskDetails.tsx
client/src/modules/Home/pages/HomePage/index.tsx
client/src/modules/Score/data/getColumns.tsx

---
Prefetch is great technique to improve site performance but it also causes multiple requests in the background. Since users mostly visited limited amount of time and we use own small EC2 instance to serve static (CDN is expensive), I want to reduce amount of requests hitting the server.

perf: disable prefetch to reduce traffic amount

---

client/src/pages/course/student/cross-check-submit.tsx
client/src/services/course.ts
server/src/routes/course/crossCheck/getTaskDetails.ts
server/src/services/crossCheck.service.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/1061
At the moment there's a problem in RS App: after passing deadline you still can try to submit your solution or cancel submission but you will get an error.  
New behaviour:  
Before deadline you can submit link to solution or cancel submission  
And after deadline you can't do that

fix: make submission after deadline unable in UI

---

client/src/components/CrossCheck/SubmittedStatus.tsx
client/src/pages/course/student/cross-check-submit.tsx

---
https://github.com/rolling-scopes/rsschool-app/issues/1084
Red text has been removed. Now there are 4 diffrent views in UI:
1. When you haven't submitted solution and deadline is not passed yet.
2. When you haven't submitted solution and deadline has passed.
3. When you have submitted solution and deadline is not passed yet.
4. When you have submitted solution and deadline has passed.
☑️ Self Check before Merge

fix: fix submission UI

---

client/src/pages/course/mentor/expel-student.tsx
client/src/services/course.ts
server/src/repositories/student.repository.ts
server/src/routes/course/student.ts

---
This fixes #1092 
Added **self-study** option and description for it:
Description for **unassign** option has been updated:
Don't have user in the wait list after applying **self-study** option:

feat: add self-study option for expel

---

client/src/components/PageLayout.tsx

---
[issue#1372](https://github.com/rolling-scopes/rsschool-app/issues/1372)
Tried to reproduce this bug on production (both Ubuntu/Windows 10, Chrome).
Haven't been able to reproduce vertical scroll, I think it's fixed already;
As for horizontal scroll - it caused by PageLayoutSimple component.
It is used on several pages, but I was able to check the fix only on this ones: 
- Expel/Unassign Student;
- #gratitude;
- …

fix: remove horizontal scroll on PageLayoutSimple 

---

client/src/components/Schedule/model.ts
client/src/components/Table/renderers.tsx

Добавлено отображение множителя очков в табличном виде расписания. Отображается, если множитель отличен от единицы. В таком виде, думаю лучше, чем заводить отдельный столбец для этого поля. Информативно и не отнимает место.
#1391 

feat: display score weight in schedule

---

client/src/modules/Score/components/ScoreTable/index.tsx
client/src/modules/Score/data/getColumns.tsx
client/src/modules/Score/data/getTaskColumns.tsx

---
[issue#1420](https://github.com/rolling-scopes/rsschool-app/issues/1420)
This PR contains work that was done in [PR#1452](https://github.com/rolling-scopes/rsschool-app/pull/1452)
Extra changes: 
- setColumns() moved inside `loadInitialData` function (fixes absence of task columns in the score table);
- ordered code inside `ScoreTable` component: declare variables/state -> function expressions -> useEffect() calls …

fix: score table bugs

---

client/src/modules/StudentDashboard/components/CommonDashboardCard.tsx
client/src/modules/StudentDashboard/components/MentorCard.tsx
client/src/modules/StudentDashboard/components/NextEventCard.tsx
client/src/modules/StudentDashboard/components/RepositoryCard.tsx
client/src/modules/StudentDashboard/components/TasksStatsCard.tsx

---
[issue#1375](https://github.com/rolling-scopes/rsschool-app/issues/1375)
Previously the title icon was removed on dashboard stats widget, this PR removes icons on all other dashboard cards for consistency as it was discussed on the related issue.

fix: remove title icons from dashboard cards

---

client/src/pages/course/admin/events.tsx
client/src/pages/course/admin/tasks.tsx

---
https://github.com/rolling-scopes/rsschool-app/issues/1560
Root cause of the bug was presence of the `courseId` in request for update from client. `courseId` is unexpected in new UpdateCourseTaskDto so this led to BAD_REQUEST response

Fix: remove courseId from request body

---

client/src/components/Forms/MarkdownInput.tsx
client/src/pages/course/student/cross-check-review.tsx

---
При проверки работ на кросс-чеке нет возможности дополнить комментарий с разметкой markdown. Если необходимо дополнить комментарий, то не получится полностью скопировать его через `ctrl + c`. И приходится заново находить форму и проставлять крестики в выполненных пунктах.
Предлагаю добавить в комментарии кнопку , которая позволит по клику перенести комментарии в заполняемую проверяющим форму.
Кнопка с синим фоном …

feat: add amend button for historical comment

---

client/src/pages/course/admin/cross-check-table.tsx
client/src/services/course.ts

---
[issue#1510](https://github.com/rolling-scopes/rsschool-app/issues/1510)
As was mentioned in [this PR](https://github.com/rolling-scopes/rsschool-app/pull/1522) problem caused by `orderBy` been an array, therefore request contains two orderBy queries and backend expects single value, so I figured it must be a client side problem and fixed it there. 

fix: cross-check table sorters

---

client/src/components/CrossCheck/CrossCheckAssignmentLink.tsx

---
При проверки работ на кросс-чеке, если кликнуть на никнейм, то откроется профиль студента в дискорде.

feat: implement opening profile by clicking on discord name

---

client/src/modules/Score/components/ScoreTable/index.tsx

---
https://github.com/rolling-scopes/rsschool-app/issues/1681
Root cause of the bug is Antd behaviour when after pressing Enter key antd fires 2 consequent `change` events - with `filter` and `sort` actions. In this case sort action receives outdated filters which leads to request for old data. This bug (feature?) already submitted to antd repo https://github.com/ant-design/ant-design/issues/37334 .
Fix provides …

Fix: score columns filtering on Enter keypress

---

client/src/components/CopyToClipboardButton.tsx
client/src/components/CrossCheck/CrossCheckAssignmentLink.tsx
client/src/components/CrossCheck/StudentContacts.tsx
client/src/components/CrossCheckComments.tsx
client/src/components/GithubUserLink.tsx
client/src/components/Icons/ScoreIcon.tsx
client/src/components/__tests__/CrossCheckComments.test.tsx
client/src/components/__tests__/__snapshots__/CrossCheckComments.test.tsx.snap
client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx
client/src/pages/course/student/cross-check-review.tsx
client/src/services/course.ts
server/src/services/taskResults.service.ts

---
#719
Из issues #719 реализовал 2 пункт (`Добавить отображения даты проверки`). 1 пункт уже есть в rs app в виде блокирующей кнопки.
Реализовано:
- Кнопка показать / скрыть контакты
- Отображения даты последней проверки
- Иконка с разным цветом в зависимости от количество баллов
- Максимальная оценка за таск
- Дискорд аккаунт проверяющего
- sticky аватарка
<details> 
<summary>Устаревший IMG</summary>
</details> …

feat(cross-check): add check date, maximum score, contacts, switch of contact visibility, score icon

---

client/src/pages/course/student/auto-test.tsx

---
[Auto-tests: Поломалась верстка авто-тестов в мобильной версии](https://github.com/rolling-scopes/rsschool-app/issues/1708)
* `ellipsis: true` breaks layout for mobile resolution
* changed width in px to % to make more responsive for mobile resolutions
* Empty state:
* With data:
* Empty state:
* With data:

fix(auto-test): update table sizes, remove ellipsis

---

client/src/modules/Schedule/components/TableView/TableView.test.tsx
client/src/modules/Schedule/components/TableView/TableView.tsx

---
Fix for: #1737 
- When click "Reset" in tags filter, page is broken

fix(table-view): should not break page when filter is null

---

client/src/pages/course/student/auto-test.tsx
client/src/pages/course/student/dashboard.tsx
client/src/pages/course/student/interviews.tsx

---
https://github.com/rolling-scopes/rsschool-app/issues/1704
Changed the background color for the required pages + increased the size of the page content for better visual appearance.
- Dashboard page  
- Before  
- After  
- Interviews page  
- Before  
- After  
- Auto-tests page  
- Before  
- After  

Change students pages background

---

client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx

---
[_Describe the source of requirement, like related issue link._](https://github.com/rolling-scopes/rsschool-app/issues/1800)
Set default time for startDate - 00:00 and 23:59 for endDate while task creation

fix: default time for creating course tasks

---

nestjs/package.json
nestjs/src/courses/course-schedule/course-schedule.service.spec.ts
nestjs/src/courses/course-schedule/course-schedule.service.ts

---
#1816 
#1822 
#1824 
1. Implemented cross-check schedule items status calculation according to [schema](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=131180%3A442782)
2. Covered it with tests
3. Fixed bug when cross-check items were without score-related data

Fix cross check items flow

---

nestjs/src/courses/mentors/mentors.service.ts

---
-
Fix bug: get random task is based on current mentor id and when different mentors get for review random solutions, the same solution is requested for these mentors.

fix(mentor-dashboard): get random solution

---

nestjs/src/courses/course-tasks/course-tasks.controller.ts

---
#1712 
New auto-test page requires detailed task data on main page (`public` field from `attributes` json of task), but api `getCourseTasksDetailed` route was under RoleGuard and students were redirecting to `/login` page when open this new auto-test page.

fix(auto-test): redirection to login when student

---

client/src/modules/CrossCheck/components/CrossCheckCriteriaForm.tsx
client/src/modules/CrossCheck/hooks/useCriteriaState.ts
client/src/pages/course/student/cross-check-review.tsx

---
Удалил `score` из хука `useCriteriaState` т.к. он не сохраняет актуальное количество очков при проверки работ через форму. И можно спутать `score` из хука  с `score` в отправляемой форме на сервер.

refactor(cross-check): delete unnecessary score

---

server/src/routes/profile/info.ts
server/src/routes/profile/permissions.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2025
Root cause of the bug was broken mechanics of detecting mentor => requesting user wasn't detected as course manager for courses on which requested user is mentoring

Fix: Allow course manager to see course mentors

---

nestjs/src/courses/mentors/mentors.controller.ts
server/src/routes/profile/permissions.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2051
After this fix course managers will be able to see profiles of users that are applied as mentors for course manager's course but not applied yet.

Allow course manager to see profiles of mentors from registry

---

nestjs/src/disciplines/disciplines.controller.test.ts
nestjs/src/disciplines/disciplines.module.ts
nestjs/src/disciplines/disciplines.service.test.ts
nestjs/src/disciplines/disciplines.service.ts
nestjs/src/registry/registry.controller.ts
nestjs/src/registry/registry.module.ts
nestjs/src/registry/registry.service.ts
server/src/routes/profile/permissions.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2095
First part of mentors visibility: course managers and supervisors are able to see mentors that submitted to mentorship by discipline without prefered course.
For example:
1. **John Doe** is supervisor/manager of Node.js course
2. **Flavie Toy** has submitted as mentor for Node.js **discipline** without selection of preferred **course**
3. **Anjali Dooley** …

Show mentors by discipline

---

client/src/components/TooltipedButton.tsx
client/src/modules/AutoTest/components/Exercise/Exercise.tsx

---
Add validation error tooltip to auto test submit button

feat: add validation error tooltip to auto test submit button

---

client/src/api/api.ts
nestjs/src/courses/cross-checks/course-cross-checks.controller.ts
nestjs/src/spec.json

fix: update cross-check api

---

server/src/services/course.service.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2138

Feature: Cross-Check distribute only active students

---

client/src/api/api.ts
client/src/services/course.ts
nestjs/src/courses/courses.module.ts
nestjs/src/courses/interviews/dto/available-student.dto.ts
nestjs/src/courses/interviews/dto/get-interview-feedback.dto.ts
nestjs/src/courses/interviews/dto/put-interview-feedback.dto.ts
nestjs/src/courses/interviews/index.ts
nestjs/src/courses/interviews/interviewFeedback.service.ts
nestjs/src/courses/interviews/interviews.controller.ts
nestjs/src/spec.json
server/src/repositories/stageInterviewFeedback.repository.ts
server/src/routes/course/index.ts
server/src/routes/course/stageInterview/createFeedback.ts
server/src/routes/course/stageInterview/getFeedback.ts

Adds new api & marks deprecated api

feat(interview): add new api & deprecation marks to the old

---

client/src/pages/admin/tasks.tsx

---
Add row gap for Used in Courses labels in task edit form
Before
After

fix(tasks): add row gap for Used in Courses

---

client/src/modules/Score/components/ScoreTable/index.tsx
client/src/modules/Score/hooks/useScorePaging.tsx

---
Related issue #2241
Using as an example fields cityName and mentor,
corrected filters in score page, with putting in newQuery githubId, name and using it to set filters in loadInitialData.

fix: correct score filters (github and name)

---

client/src/components/Header.tsx
client/src/components/PageLayout.tsx
client/src/modules/Course/contexts/ActiveCourseContext.tsx
client/src/modules/Course/contexts/SessionContext.test.tsx
client/src/modules/Home/pages/HomePage/index.tsx
client/src/modules/Mentor/components/MentorDashboard/MentorDashboard.test.tsx

fix: update useCourseContext

---

client/src/components/Header.tsx
client/src/modules/Admin/CourseTasks/components/index.ts
client/src/modules/Schedule/components/MobileItemCard/MobileItemCard.tsx
client/src/modules/Schedule/pages/SchedulePage/index.tsx

fix: update mobile schedule view

---

client/src/components/Header.tsx
client/src/components/Profile/CoreJsIviewsModal.tsx
client/src/components/Profile/MentorStatsModal.tsx
client/src/components/Profile/__test__/CoreJsIviewsCard.test.tsx
client/src/components/Profile/__test__/MentorStatsCard.test.tsx
client/src/modules/AutoTest/components/Coding/Coding.test.tsx
client/src/modules/CrossCheck/__tests__/AddCriteriaForCrossCheck.test.tsx
client/src/modules/CrossCheck/__tests__/UploadCriteriaJSON.test.tsx
client/src/modules/Mentor/components/MentorDashboard/MentorDashboard.test.tsx
client/src/modules/MentorRegistry/components/MentorRegistryTableContainer.tsx
client/src/modules/Opportunities/components/PublicLink/index.test.tsx
client/src/modules/Opportunities/components/ViewCv/CoursesSection/index.tsx
client/src/modules/Registry/components/Cards/PersonalInfo/PersonalInfo.test.tsx
client/src/modules/Registry/components/FormSections/GeneralSection/GeneralSection.test.tsx
client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.test.tsx
client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.tsx
client/src/modules/Schedule/components/AdditionalActions/helpers.ts
client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.test.tsx

---
Ain't this beautiful? ;)
BREAKING CHANGES:
in order to migrate to `menu` on `Dropdown` on `Header` component had to use `:has()` selector to style current route active menu item, which won't work on `Firefox`. Looks like `menu` has less flexibility compared to `overlay`, or I simply haven't found the way. So we either leave it that way, or should I change it back to `overlay`?
⚠️ Please check all items below before …

test & refactor: fix tests warnings

---

client/src/pages/course/submit-scores.tsx

---
Remove Multiple attribute, add access attribute. add type for param in onChange handler.

fix(submit-score): remove multiple file upload attribute, add accept attribute

---

client/src/components/Forms/ModalForm.tsx
client/src/hooks/index.ts
client/src/hooks/useModal/useModalForm.tsx
client/src/modules/Tasks/components/TaskModal/TaskModal.test.tsx
client/src/modules/Tasks/components/TaskModal/TaskModal.tsx
client/src/modules/Tasks/components/TaskSettings/TaskSettings.test.tsx
client/src/modules/Tasks/components/TaskSettings/TaskSettings.tsx
client/src/modules/Tasks/constants.ts
client/src/modules/Tasks/pages/TasksPage/TasksPage.tsx
client/src/modules/Tasks/types.ts

---
[PR#2305](https://github.com/rolling-scopes/rsschool-app/pull/2305)
[issue#1980](https://github.com/rolling-scopes/rsschool-app/issues/1980)
- remove redundant `setState` call on form inputs changes
- add criteria settings set based on task type
UI Update:

feat: add criteria settings set based on task type

---

client/src/modules/Score/data/getTaskColumns.tsx

---
[issue#2302](https://github.com/rolling-scopes/rsschool-app/issues/2302)
- set `min-width: 235px` so popup won't shrink, which fixes flickering;
- set `position: fixed` instead of `absolute`, which fixes `body` overflow(horizontal);
- set score coefficient `toFixed(2)`, same as on schedule table;

fix: adjust popup positioning

---

.github/workflows/deploy-bumblebee.yaml
.github/workflows/deploy-sloths.yaml
.github/workflows/deploy.yaml
.github/workflows/nextjs_bundle_analysis.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_close.yml
client/Dockerfile
client/Dockerfile.lambda
nestjs/Dockerfile
nestjs/Dockerfile.lambda
package-lock.json
server/Dockerfile
server/Dockerfile.lambda
server/package.json
setup/docker-compose.yml

chore: node 20

---

client/src/modules/CrossCheck/components/SolutionReview/MessageSendingPanel/MessageSendingPanel.tsx
client/src/modules/CrossCheck/components/criteria/CrossCheckCriteria.tsx
client/src/modules/CrossCheck/components/criteria/SubtaskCriteria.tsx
client/src/modules/CrossCheck/index.tsx
client/src/modules/CrossCheck/utils/getCriteriaStatusColor.ts

feat: add criteria status color; increase message length

---

client/src/modules/AutoTest/components/VerificationInformation/VerificationInformation.test.tsx
client/src/modules/AutoTest/components/VerificationInformation/VerificationInformation.tsx

---
https://github.com/rolling-scopes/rsschool-app/issues/2375
Move 'start task' and 'show results' buttons above the table according to the solution proposed in the comments to the issue.
<details>
<summary>Screenshots with 3 and 2 buttons for different viewport widths:</summary>
<br>
two buttons, 768
three buttons, 768
two buttons, 320
three buttons, 320
</details>

fix: move 'start task' and 'show results' buttons above table

---

client/src/api/api.ts
client/src/components/Sider/data/menuItems.tsx
client/src/modules/AdminDashboard/components/StudentsCountriesCard/StudentsCountriesCard.tsx
client/src/modules/AdminDashboard/components/StudentsCountriesCard/StudentsCountriesChart.tsx
client/src/modules/AdminDashboard/components/StudentsCountriesCard/index.tsx
client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsCard.tsx
client/src/modules/AdminDashboard/components/StudentsStatsCard/StudentsStatsChart.tsx
client/src/modules/AdminDashboard/components/StudentsStatsCard/index.tsx
client/src/modules/AdminDashboard/hooks/index.ts
client/src/modules/AdminDashboard/hooks/useCourseStats/useCourseStats.tsx
client/src/modules/AdminDashboard/index.tsx
client/src/modules/AdminDashboard/pages/AdminDashboard.tsx
client/src/pages/course/admin/dashboard.tsx
nestjs/src/courses/stats/course-stats.controller.ts
nestjs/src/courses/stats/course-stats.service.ts
nestjs/src/courses/stats/dto/index.ts
nestjs/src/courses/stats/dto/students-countries-stats.dto.ts
nestjs/src/spec.json

feat: create students countries stats widget

---

nestjs/src/courses/stats/course-stats.service.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2473
If amount of eligible students is greater than 100% => it should be 100% (as alternative solution we can show amount of eligible students vs all students, but I think it doesn't make much sense)

Show correct eligible students amount

---

client/package.json
client/src/__tests__/__snapshots__/ProfilePage.test.tsx.snap
client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/AboutCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/CommonCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/CommonCardWithSettingsModal.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/ContactsCardForm.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/MainCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/MentorStatsCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/ProfileSettingsModal.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/PublicFeedbackCard.test.tsx.snap
client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap
client/src/modules/CrossCheck/__tests__/__snapshots__/AddCriteriaForCrossCheck.test.tsx.snap
client/src/pages/_document.tsx
client/src/pages/login/index.tsx
package-lock.json

---
https://github.com/rolling-scopes/rsschool-app/issues/2452
This happens because of SSR, we don't need it for this page  
UPD: this is a global problem related with how Antd works with SSR, however, this is a small page that users see first/often, so I think it still worth to fix it at least here
UPD [2]: It seems that there's alternative approach of styles loading without breaking SSR …

Fix no styles on login page

---

client/src/modules/StudentDashboard/components/MentorInfo/MentorInfo.tsx

fix: MentorInfo component to render filledContacts correctly

---

client/src/api/api.ts
client/src/components/UserSearch.tsx
client/src/modules/MentorTasksReview/components/AssignReviewerModal/AssignReviewerModal.tsx
client/src/modules/MentorTasksReview/components/AssignReviewerModal/index.ts
client/src/modules/MentorTasksReview/components/ReviewsTable/index.tsx
client/src/modules/MentorTasksReview/components/ReviewsTable/renderers.tsx
client/src/modules/MentorTasksReview/pages/MentorTasksReview.tsx
nestjs/src/courses/mentor-reviews/dto/mentor-review-assign.dto.ts
nestjs/src/courses/mentor-reviews/dto/mentor-reviews.dto.ts
nestjs/src/courses/mentor-reviews/mentor-reviews.controller.ts
nestjs/src/courses/mentor-reviews/mentor-reviews.service.ts
nestjs/src/courses/mentors/mentors.service.ts
nestjs/src/spec.json

---
@valerydluski 
- Add possibility to assign reviewer

feat: Mentor Task Reviews - Assign reviewer

---

client/src/modules/MentorTasksReview/components/ReviewsTable/index.tsx
client/src/modules/MentorTasksReview/components/ReviewsTable/renderers.tsx
client/src/modules/MentorTasksReview/pages/MentorTasksReview.tsx
nestjs/src/courses/mentor-reviews/mentor-reviews.controller.ts

fix: update assign checker permission

---

.github/workflows/deploy-bumblebee.yaml
.github/workflows/deploy-sloths.yaml
.github/workflows/deploy.yaml
.github/workflows/nextjs_bundle_analysis.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_close.yml
.github/workflows/renovate.yml
nestjs/src/certificates/certificates.service.ts
nestjs/src/config/config.service.ts
nestjs/src/courses/courses.service.ts
nestjs/src/courses/dto/export-course.dto.ts
nestjs/src/courses/dto/index.ts

feat: export courses to s3 bucket

---

client/src/pages/course/student/cross-check-review.tsx
server/src/routes/course/crossCheck/createResult.ts

fix: Do not apply cross-check score more than max score of a task

---

client/src/api/api.ts
client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx
client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx
nestjs/src/courses/course-tasks/dto/course-task.dto.ts
nestjs/src/spec.json
server/src/models/courseTask.ts

---
https://github.com/rolling-scopes/rsschool-app/issues/2545
Added "Github PR in URL" validation that is disabled by default and can be combined with "Github Id in URL" option
Before  
After  

Add Github PR in URL validation

---

client/src/pages/course/admin/stage-interviews.tsx

---
- Related Issue #2596
- Closes #2596
BEFORE:
It was not possible to use sizeChanger control with an affect on the page.
sizeChanger control is displayed when items.count >50.
AFTER:
default page size set to ant table pagination,
also displaying of the total items was improved.
So user can change page size and work with interviews page more comfortably.
sizeChanger control is displayed all the time.
⚠️ Please check …

fix: pagination for stage interview page

---

client/src/modules/Course/contexts/ActiveCourseContext.tsx

---
Closes #2595
before the fix
- useAsync called when router was not ready and alias undefined while it was in page URL
after the fix
- fetch data and set active course only when router is ready, so if an alias in the url, it is taken into account.
Also, the proper course is set to localstorage sharing the active course accross the pages

fix: set proper active course having alias in url

---

client/src/modules/CrossCheck/UploadCriteriaJSON.tsx

**Issue**:
https://github.com/rolling-scopes/rsschool-app/issues/2699
Root cause of the issue is the default behavior of `Upload` component – it sends file to server with POST request. We don't need it here, because we handle file content client-side using `FileReader` API. Override of default behavior with customRequest fixes issue.

fix: don't send request to server on criteria upload

---

client/src/modules/CrossCheck/AddCriteriaForCrossCheck.tsx

**Issue**:
https://github.com/rolling-scopes/rsschool-app/issues/2700
Scope of changes:  
1. Fixed unexpected partial change of selected criteria – now type is preserved. It's better than switch to Title type on each item save. Mostly you need to add one title and then multiple subtasks/penalties, constant re-selection of subtask/penalty type is not convenient.
2. Prohibit entering non-numeric values into inputs

Fix: cross-check criteria item type issue

---

client/src/api/api.ts
client/src/pages/course/mentor/confirm.tsx
nestjs/src/discord-servers/discord-servers.controller.ts
nestjs/src/discord-servers/discord-servers.service.ts
nestjs/src/spec.json

**Issue**:
Issue - #2737
After the second step, the mentor can access the right course FAQ chat link. 

fix: change mentors telegram chat appearing after mentor registration to refer to the correct course

---

client/src/api/api.ts
client/src/pages/course/mentor/confirm.tsx
nestjs/src/discord-servers/discord-servers.controller.ts
nestjs/src/spec.json

For megre before: #2748
**Issue**:
The getDiscordServerById endpoint should be renamed for improved readability and clarity of the code.
Rename the endpoint, update api and frontend (confirm.tsx).

refactor: rename getDiscordServerById endpoint to getInviteLinkByDiscordServerId with URL invite/:id

---

client/src/modules/Mentor/components/Instructions/Instructions.tsx
client/src/modules/Mentor/components/Instructions/constants.ts
client/src/modules/Mentor/components/Instructions/renderers.tsx
client/src/modules/Mentor/components/MentorDashboard/MentorDashboard.tsx

For megre after: #2750
**Issue**:
#2737 
Now you can access the right course FAQ telegram chat link on the mentor's dashboard page.

fix: change telegram link on the mentor's dashboard page

---

client/src/modules/CrossCheck/components/criteria/CrossCheckCriteria.tsx
client/src/modules/CrossCheck/components/criteria/SubtaskCriteria.tsx

**Issue**:
Issue: https://github.com/rolling-scopes/rsschool-app/issues/2775
Original message: https://github.com/rolling-scopes/rsschool-app/issues/2763#issuecomment-3112534622
Before:
After:

FIX: wrong colors for cross-check detailed view

---

client/src/components/Profile/StudentLeaveCourse.tsx
client/src/components/Profile/StudentStatsCard.tsx
client/src/components/ScoreCard.tsx
client/src/modules/Opportunities/components/NoConsentView/index.tsx

**Issue**:
- Interview scorecards: https://github.com/rolling-scopes/rsschool-app/issues/2777 
- Leave the course modal window https://github.com/rolling-scopes/rsschool-app/issues/2774
- Tooltips appear underneath the modal window https://github.com/rolling-scopes/rsschool-app/issues/2769
Original messages: https://github.com/rolling-scopes/rsschool-app/issues/2763#issuecomment-3112577138, https://github.com/rolling-scopes/rsschool-app/issues/2763#issuecomment-3108583701 and https://github.com/rolling-scopes/rsschool-app/issues/2763#issuecomment-3109140526
CoreJS interview scorecards looked ugly with dark theme:
Before:
After:
Leave the course modal window:
Before:
After:
Tooltips placement
Before:
After:

Proper colors in dark theme for ScoreCard, Leaving course modal icon and tootip placement for the CV modal

---

client/src/modules/Home/data/links.tsx

**Issue**:
[Update course link icons on the Homepage](https://github.com/rolling-scopes/rsschool-app/issues/2789)
Original message: https://github.com/rolling-scopes/rsschool-app/issues/2768#issuecomment-3109180377
Some icons filled with white inside.
| | Light | Dark |
| -- | -- | -- |
| Before | <img width="595" height="1041" alt="before light" src="https://github.com/user-attachments/assets/051ce7e9-dccc-437a-bf1b-22fa991e31f0" /> | <img width="589" height="1037" alt="before dark" src="https://github.com/user-attachments/assets/46190aaa-7933-4420-a4a9-f885c150beb6" /> |
| After |  <img width="583" height="1035" alt="after light" src="https://github.com/user-attachments/assets/f6734b6b-8013-4e20-b4c5-8cec253ae80d" /> |  <img width="584" height="1045" alt="after dark" …

Replace TwoTone icons with Outlined icons on the Home page

---

client/src/components/Forms/Heroes/index.tsx

**Issue**:
[_Link to the relevant GitHub Issue (e.g., `#123` for issue number 123)._](https://github.com/rolling-scopes/rsschool-app/issues/2828)
Wrong background color on the heroes page cards.
**Done**
1. Change heroes page cards background to the appropriate
2. Tiny improvements of the badges animation
[Screencast_20250929_152522.webm](https://github.com/user-attachments/assets/141e06aa-187e-472b-8d0b-674a88e38175)

Dark theme bug on heroes page

---

client/src/modules/Score/components/ScoreTable/index.tsx

**Issue**:
Initial issues: #2066
The counter on the student list tabs doesn't show the number of the active and inactive students due to the API permissions. Current PR changes the API for getting this data.

FIX users counter permissions
